// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with otp_ctrl_mmap.hjson and fuses.hjson
use zeroize::Zeroize;
/// Fuses contains the data in the OTP controller laid out as described in the controller configuration.
#[derive(Zeroize)]
pub struct Fuses {
    /// Software manufacturing partition.
    #[zeroize(skip)]
    pub sw_test_unlock_partition: [u8; 72],

    /// Software manufacturing partition.
    #[zeroize(skip)]
    pub sw_manuf_partition: [u8; 520],

    /// Secret life-cycle unlock token partition.
    pub secret_lc_transition_partition: [u8; 184],

    /// SVN Partition.
    #[zeroize(skip)]
    pub svn_partition: [u8; 40],

    /// Vendor test partition.
    #[zeroize(skip)]
    pub vendor_test_partition: [u8; 64],

    /// Vendor hashes manufacturing partition.
    #[zeroize(skip)]
    pub vendor_hashes_manuf_partition: [u8; 64],

    /// Vendor hashes production partition.
    #[zeroize(skip)]
    pub vendor_hashes_prod_partition: [u8; 864],

    /// Vendor revocations production partition.
    #[zeroize(skip)]
    pub vendor_revocations_prod_partition: [u8; 216],

    /// Vendor secret production partition.
    pub vendor_secret_prod_partition: [u8; 528],

    /// Vendor non-secret production partition.
    #[zeroize(skip)]
    pub vendor_non_secret_prod_partition: [u8; 520],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 0.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_0: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 1.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_1: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 2.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_2: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 3.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_3: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 4.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_4: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 5.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_5: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 6.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_6: [u8; 48],

    /// OCP L.O.C.K Hard Epoch Key (HEK) ratchet seed slot 7.
    #[zeroize(skip)]
    pub cptra_ss_lock_hek_prod_7: [u8; 48],
}
impl Fuses {
    pub fn cptra_ss_manuf_debug_unlock_token(&self) -> &[u8] {
        &self.sw_test_unlock_partition[0..64]
    }
    pub fn cptra_core_anti_rollback_disable(&self) -> &[u8] {
        &self.sw_manuf_partition[0..4]
    }
    pub fn cptra_core_idevid_cert_idevid_attr(&self) -> &[u8] {
        &self.sw_manuf_partition[4..100]
    }
    pub fn soc_specific_idevid_certificate(&self) -> &[u8] {
        &self.sw_manuf_partition[100..104]
    }
    pub fn cptra_core_idevid_manuf_hsm_identifier(&self) -> &[u8] {
        &self.sw_manuf_partition[104..120]
    }
    pub fn cptra_core_soc_stepping_id(&self) -> &[u8] {
        &self.sw_manuf_partition[120..124]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_0(&self) -> &[u8] {
        &self.sw_manuf_partition[124..172]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_1(&self) -> &[u8] {
        &self.sw_manuf_partition[172..220]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_2(&self) -> &[u8] {
        &self.sw_manuf_partition[220..268]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_3(&self) -> &[u8] {
        &self.sw_manuf_partition[268..316]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_4(&self) -> &[u8] {
        &self.sw_manuf_partition[316..364]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_5(&self) -> &[u8] {
        &self.sw_manuf_partition[364..412]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_6(&self) -> &[u8] {
        &self.sw_manuf_partition[412..460]
    }
    pub fn cptra_ss_prod_debug_unlock_pks_7(&self) -> &[u8] {
        &self.sw_manuf_partition[460..508]
    }
    pub fn cptra_ss_test_unlock_token_1(&self) -> &[u8] {
        &self.secret_lc_transition_partition[0..16]
    }
    pub fn cptra_ss_test_unlock_token_2(&self) -> &[u8] {
        &self.secret_lc_transition_partition[16..32]
    }
    pub fn cptra_ss_test_unlock_token_3(&self) -> &[u8] {
        &self.secret_lc_transition_partition[32..48]
    }
    pub fn cptra_ss_test_unlock_token_4(&self) -> &[u8] {
        &self.secret_lc_transition_partition[48..64]
    }
    pub fn cptra_ss_test_unlock_token_5(&self) -> &[u8] {
        &self.secret_lc_transition_partition[64..80]
    }
    pub fn cptra_ss_test_unlock_token_6(&self) -> &[u8] {
        &self.secret_lc_transition_partition[80..96]
    }
    pub fn cptra_ss_test_unlock_token_7(&self) -> &[u8] {
        &self.secret_lc_transition_partition[96..112]
    }
    pub fn cptra_ss_test_exit_to_manuf_token(&self) -> &[u8] {
        &self.secret_lc_transition_partition[112..128]
    }
    pub fn cptra_ss_manuf_to_prod_token(&self) -> &[u8] {
        &self.secret_lc_transition_partition[128..144]
    }
    pub fn cptra_ss_prod_to_prod_end_token(&self) -> &[u8] {
        &self.secret_lc_transition_partition[144..160]
    }
    pub fn cptra_ss_rma_token(&self) -> &[u8] {
        &self.secret_lc_transition_partition[160..176]
    }
    pub fn cptra_core_fmc_key_manifest_svn(&self) -> &[u8] {
        &self.svn_partition[0..4]
    }
    pub fn cptra_core_runtime_svn(&self) -> &[u8] {
        &self.svn_partition[4..20]
    }
    pub fn cptra_core_soc_manifest_svn(&self) -> &[u8] {
        &self.svn_partition[20..36]
    }
    pub fn cptra_core_soc_manifest_max_svn(&self) -> &[u8] {
        &self.svn_partition[36..40]
    }
    pub fn vendor_test(&self) -> &[u8] {
        &self.vendor_test_partition[0..32]
    }
    pub fn cptra_core_vendor_pk_hash_0(&self) -> &[u8] {
        &self.vendor_hashes_manuf_partition[0..48]
    }
    pub fn cptra_core_pqc_key_type_0(&self) -> &[u8] {
        &self.vendor_hashes_manuf_partition[48..52]
    }
    pub fn cptra_ss_owner_pk_hash(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[0..48]
    }
    pub fn cptra_ss_owner_pqc_key_type(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[48..52]
    }
    pub fn cptra_ss_owner_pk_hash_valid(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[52..56]
    }
    pub fn cptra_core_vendor_pk_hash_1(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[56..104]
    }
    pub fn cptra_core_pqc_key_type_1(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[104..108]
    }
    pub fn cptra_core_vendor_pk_hash_2(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[108..156]
    }
    pub fn cptra_core_pqc_key_type_2(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[156..160]
    }
    pub fn cptra_core_vendor_pk_hash_3(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[160..208]
    }
    pub fn cptra_core_pqc_key_type_3(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[208..212]
    }
    pub fn cptra_core_vendor_pk_hash_4(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[212..260]
    }
    pub fn cptra_core_pqc_key_type_4(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[260..264]
    }
    pub fn cptra_core_vendor_pk_hash_5(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[264..312]
    }
    pub fn cptra_core_pqc_key_type_5(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[312..316]
    }
    pub fn cptra_core_vendor_pk_hash_6(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[316..364]
    }
    pub fn cptra_core_pqc_key_type_6(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[364..368]
    }
    pub fn cptra_core_vendor_pk_hash_7(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[368..416]
    }
    pub fn cptra_core_pqc_key_type_7(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[416..420]
    }
    pub fn cptra_core_vendor_pk_hash_8(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[420..468]
    }
    pub fn cptra_core_pqc_key_type_8(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[468..472]
    }
    pub fn cptra_core_vendor_pk_hash_9(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[472..520]
    }
    pub fn cptra_core_pqc_key_type_9(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[520..524]
    }
    pub fn cptra_core_vendor_pk_hash_10(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[524..572]
    }
    pub fn cptra_core_pqc_key_type_10(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[572..576]
    }
    pub fn cptra_core_vendor_pk_hash_11(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[576..624]
    }
    pub fn cptra_core_pqc_key_type_11(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[624..628]
    }
    pub fn cptra_core_vendor_pk_hash_12(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[628..676]
    }
    pub fn cptra_core_pqc_key_type_12(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[676..680]
    }
    pub fn cptra_core_vendor_pk_hash_13(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[680..728]
    }
    pub fn cptra_core_pqc_key_type_13(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[728..732]
    }
    pub fn cptra_core_vendor_pk_hash_14(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[732..780]
    }
    pub fn cptra_core_pqc_key_type_14(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[780..784]
    }
    pub fn cptra_core_vendor_pk_hash_15(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[784..832]
    }
    pub fn cptra_core_pqc_key_type_15(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[832..836]
    }
    pub fn cptra_core_vendor_pk_hash_valid(&self) -> &[u8] {
        &self.vendor_hashes_prod_partition[836..852]
    }
    pub fn cptra_ss_owner_ecc_revocation(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[0..4]
    }
    pub fn cptra_ss_owner_lms_revocation(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[4..8]
    }
    pub fn cptra_ss_owner_mldsa_revocation(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[8..12]
    }
    pub fn cptra_core_ecc_revocation_0(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[12..16]
    }
    pub fn cptra_core_lms_revocation_0(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[16..20]
    }
    pub fn cptra_core_mldsa_revocation_0(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[20..24]
    }
    pub fn cptra_core_ecc_revocation_1(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[24..28]
    }
    pub fn cptra_core_lms_revocation_1(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[28..32]
    }
    pub fn cptra_core_mldsa_revocation_1(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[32..36]
    }
    pub fn cptra_core_ecc_revocation_2(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[36..40]
    }
    pub fn cptra_core_lms_revocation_2(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[40..44]
    }
    pub fn cptra_core_mldsa_revocation_2(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[44..48]
    }
    pub fn cptra_core_ecc_revocation_3(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[48..52]
    }
    pub fn cptra_core_lms_revocation_3(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[52..56]
    }
    pub fn cptra_core_mldsa_revocation_3(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[56..60]
    }
    pub fn cptra_core_ecc_revocation_4(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[60..64]
    }
    pub fn cptra_core_lms_revocation_4(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[64..68]
    }
    pub fn cptra_core_mldsa_revocation_4(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[68..72]
    }
    pub fn cptra_core_ecc_revocation_5(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[72..76]
    }
    pub fn cptra_core_lms_revocation_5(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[76..80]
    }
    pub fn cptra_core_mldsa_revocation_5(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[80..84]
    }
    pub fn cptra_core_ecc_revocation_6(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[84..88]
    }
    pub fn cptra_core_lms_revocation_6(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[88..92]
    }
    pub fn cptra_core_mldsa_revocation_6(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[92..96]
    }
    pub fn cptra_core_ecc_revocation_7(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[96..100]
    }
    pub fn cptra_core_lms_revocation_7(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[100..104]
    }
    pub fn cptra_core_mldsa_revocation_7(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[104..108]
    }
    pub fn cptra_core_ecc_revocation_8(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[108..112]
    }
    pub fn cptra_core_lms_revocation_8(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[112..116]
    }
    pub fn cptra_core_mldsa_revocation_8(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[116..120]
    }
    pub fn cptra_core_ecc_revocation_9(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[120..124]
    }
    pub fn cptra_core_lms_revocation_9(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[124..128]
    }
    pub fn cptra_core_mldsa_revocation_9(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[128..132]
    }
    pub fn cptra_core_ecc_revocation_10(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[132..136]
    }
    pub fn cptra_core_lms_revocation_10(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[136..140]
    }
    pub fn cptra_core_mldsa_revocation_10(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[140..144]
    }
    pub fn cptra_core_ecc_revocation_11(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[144..148]
    }
    pub fn cptra_core_lms_revocation_11(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[148..152]
    }
    pub fn cptra_core_mldsa_revocation_11(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[152..156]
    }
    pub fn cptra_core_ecc_revocation_12(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[156..160]
    }
    pub fn cptra_core_lms_revocation_12(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[160..164]
    }
    pub fn cptra_core_mldsa_revocation_12(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[164..168]
    }
    pub fn cptra_core_ecc_revocation_13(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[168..172]
    }
    pub fn cptra_core_lms_revocation_13(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[172..176]
    }
    pub fn cptra_core_mldsa_revocation_13(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[176..180]
    }
    pub fn cptra_core_ecc_revocation_14(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[180..184]
    }
    pub fn cptra_core_lms_revocation_14(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[184..188]
    }
    pub fn cptra_core_mldsa_revocation_14(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[188..192]
    }
    pub fn cptra_core_ecc_revocation_15(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[192..196]
    }
    pub fn cptra_core_lms_revocation_15(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[196..200]
    }
    pub fn cptra_core_mldsa_revocation_15(&self) -> &[u8] {
        &self.vendor_revocations_prod_partition[200..204]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_0(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[0..32]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_1(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[32..64]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_2(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[64..96]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_3(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[96..128]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_4(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[128..160]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_5(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[160..192]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_6(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[192..224]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_7(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[224..256]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_8(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[256..288]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_9(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[288..320]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_10(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[320..352]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_11(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[352..384]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_12(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[384..416]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_13(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[416..448]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_14(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[448..480]
    }
    pub fn cptra_ss_vendor_specific_secret_fuse_15(&self) -> &[u8] {
        &self.vendor_secret_prod_partition[480..512]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_0(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[0..32]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_1(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[32..64]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_2(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[64..96]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_3(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[96..128]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_4(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[128..160]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_5(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[160..192]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_6(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[192..224]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_7(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[224..256]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_8(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[256..288]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_9(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[288..320]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_10(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[320..352]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_11(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[352..384]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_12(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[384..416]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_13(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[416..448]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_14(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[448..480]
    }
    pub fn cptra_ss_vendor_specific_non_secret_fuse_15(&self) -> &[u8] {
        &self.vendor_non_secret_prod_partition[480..512]
    }
    pub fn cptra_ss_lock_hek_prod_0_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_0[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_1_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_1[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_2_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_2[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_3_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_3[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_4_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_4[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_5_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_5[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_6_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_6[0..32]
    }
    pub fn cptra_ss_lock_hek_prod_7_ratchet_seed(&self) -> &[u8] {
        &self.cptra_ss_lock_hek_prod_7[0..32]
    }
}
impl Default for Fuses {
    fn default() -> Self {
        Self {
            sw_test_unlock_partition: [0; 72],
            sw_manuf_partition: [0; 520],
            secret_lc_transition_partition: [0; 184],
            svn_partition: [0; 40],
            vendor_test_partition: [0; 64],
            vendor_hashes_manuf_partition: [0; 64],
            vendor_hashes_prod_partition: [0; 864],
            vendor_revocations_prod_partition: [0; 216],
            vendor_secret_prod_partition: [0; 528],
            vendor_non_secret_prod_partition: [0; 520],
            cptra_ss_lock_hek_prod_0: [0; 48],
            cptra_ss_lock_hek_prod_1: [0; 48],
            cptra_ss_lock_hek_prod_2: [0; 48],
            cptra_ss_lock_hek_prod_3: [0; 48],
            cptra_ss_lock_hek_prod_4: [0; 48],
            cptra_ss_lock_hek_prod_5: [0; 48],
            cptra_ss_lock_hek_prod_6: [0; 48],
            cptra_ss_lock_hek_prod_7: [0; 48],
        }
    }
}
pub const SW_TEST_UNLOCK_PARTITION_BYTE_OFFSET: usize = 0x0;
pub const SW_TEST_UNLOCK_PARTITION_BYTE_SIZE: usize = 0x48;
pub const SECRET_MANUF_PARTITION_BYTE_OFFSET: usize = 0x48;
pub const SECRET_MANUF_PARTITION_BYTE_SIZE: usize = 0x50;
pub const SECRET_PROD_PARTITION_0_BYTE_OFFSET: usize = 0x98;
pub const SECRET_PROD_PARTITION_0_BYTE_SIZE: usize = 0x18;
pub const SECRET_PROD_PARTITION_1_BYTE_OFFSET: usize = 0xb0;
pub const SECRET_PROD_PARTITION_1_BYTE_SIZE: usize = 0x18;
pub const SECRET_PROD_PARTITION_2_BYTE_OFFSET: usize = 0xc8;
pub const SECRET_PROD_PARTITION_2_BYTE_SIZE: usize = 0x18;
pub const SECRET_PROD_PARTITION_3_BYTE_OFFSET: usize = 0xe0;
pub const SECRET_PROD_PARTITION_3_BYTE_SIZE: usize = 0x18;
pub const SW_MANUF_PARTITION_BYTE_OFFSET: usize = 0xf8;
pub const SW_MANUF_PARTITION_BYTE_SIZE: usize = 0x208;
pub const SECRET_LC_TRANSITION_PARTITION_BYTE_OFFSET: usize = 0x300;
pub const SECRET_LC_TRANSITION_PARTITION_BYTE_SIZE: usize = 0xb8;
pub const SVN_PARTITION_BYTE_OFFSET: usize = 0x3b8;
pub const SVN_PARTITION_BYTE_SIZE: usize = 0x28;
pub const VENDOR_TEST_PARTITION_BYTE_OFFSET: usize = 0x3e0;
pub const VENDOR_TEST_PARTITION_BYTE_SIZE: usize = 0x40;
pub const VENDOR_HASHES_MANUF_PARTITION_BYTE_OFFSET: usize = 0x420;
pub const VENDOR_HASHES_MANUF_PARTITION_BYTE_SIZE: usize = 0x40;
pub const VENDOR_HASHES_PROD_PARTITION_BYTE_OFFSET: usize = 0x460;
pub const VENDOR_HASHES_PROD_PARTITION_BYTE_SIZE: usize = 0x360;
pub const VENDOR_REVOCATIONS_PROD_PARTITION_BYTE_OFFSET: usize = 0x7c0;
pub const VENDOR_REVOCATIONS_PROD_PARTITION_BYTE_SIZE: usize = 0xd8;
pub const VENDOR_SECRET_PROD_PARTITION_BYTE_OFFSET: usize = 0x898;
pub const VENDOR_SECRET_PROD_PARTITION_BYTE_SIZE: usize = 0x210;
pub const VENDOR_NON_SECRET_PROD_PARTITION_BYTE_OFFSET: usize = 0xaa8;
pub const VENDOR_NON_SECRET_PROD_PARTITION_BYTE_SIZE: usize = 0x208;
pub const CPTRA_SS_LOCK_HEK_PROD_0_BYTE_OFFSET: usize = 0xcb0;
pub const CPTRA_SS_LOCK_HEK_PROD_0_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_1_BYTE_OFFSET: usize = 0xce0;
pub const CPTRA_SS_LOCK_HEK_PROD_1_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_2_BYTE_OFFSET: usize = 0xd10;
pub const CPTRA_SS_LOCK_HEK_PROD_2_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_3_BYTE_OFFSET: usize = 0xd40;
pub const CPTRA_SS_LOCK_HEK_PROD_3_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_4_BYTE_OFFSET: usize = 0xd70;
pub const CPTRA_SS_LOCK_HEK_PROD_4_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_5_BYTE_OFFSET: usize = 0xda0;
pub const CPTRA_SS_LOCK_HEK_PROD_5_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_6_BYTE_OFFSET: usize = 0xdd0;
pub const CPTRA_SS_LOCK_HEK_PROD_6_BYTE_SIZE: usize = 0x30;
pub const CPTRA_SS_LOCK_HEK_PROD_7_BYTE_OFFSET: usize = 0xe00;
pub const CPTRA_SS_LOCK_HEK_PROD_7_BYTE_SIZE: usize = 0x30;
pub const LIFE_CYCLE_BYTE_OFFSET: usize = 0xe30;
pub const LIFE_CYCLE_BYTE_SIZE: usize = 0x58;

// Licensed under the Apache-2.0 license.
// Autogenerated file from fuses.hjson. Do not modify this file.

#[derive(Debug, Clone)]
pub struct Partition {
    pub num: usize,
    pub name: &'static str,
    pub dot: bool,
}
#[derive(Debug, Clone, Copy)]
pub struct Bytes(pub usize);
#[derive(Debug, Clone, Copy)]
pub struct Bits(pub usize);
#[derive(Debug, Clone)]
pub struct Fuse {
    pub name: &'static str,
    pub size: Bytes,
}
#[derive(Debug, Clone)]
pub struct FuseField {
    pub name: &'static str,
    pub bits: Bits,
}
/// Layout type for interpreting raw fuse bits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FuseLayoutType {
    Single { bits: u32 },
    OneHot { bits: u32 },
    LinearMajorityVote { bits: u32, duplication: u32 },
    OneHotLinearMajorityVote { bits: u32, duplication: u32 },
    WordMajorityVote { bits: u32, duplication: u32 },
}
/// Entry in the fuse lookup table mapping (partition, entry) to OTP location and layout.
#[derive(Debug, Clone)]
pub struct FuseEntryInfo {
    /// Partition number (index into OTP partitions)
    pub partition_num: usize,
    /// Entry number within the partition
    pub entry_num: usize,
    /// Byte offset from start of OTP
    pub byte_offset: usize,
    /// Size in bytes of the raw fuse storage
    pub byte_size: usize,
    /// Field name
    pub name: &'static str,
    /// Layout for interpreting the raw bits
    pub layout: FuseLayoutType,
}
pub const PARTITIONS: &[Partition] = &[
    Partition {
        num: 0,
        name: "SW_TEST_UNLOCK_PARTITION",
        dot: false,
    },
    Partition {
        num: 1,
        name: "SECRET_MANUF_PARTITION",
        dot: false,
    },
    Partition {
        num: 2,
        name: "SECRET_PROD_PARTITION_0",
        dot: false,
    },
    Partition {
        num: 3,
        name: "SECRET_PROD_PARTITION_1",
        dot: false,
    },
    Partition {
        num: 4,
        name: "SECRET_PROD_PARTITION_2",
        dot: false,
    },
    Partition {
        num: 5,
        name: "SECRET_PROD_PARTITION_3",
        dot: false,
    },
    Partition {
        num: 6,
        name: "SW_MANUF_PARTITION",
        dot: false,
    },
    Partition {
        num: 7,
        name: "SECRET_LC_TRANSITION_PARTITION",
        dot: false,
    },
    Partition {
        num: 8,
        name: "SVN_PARTITION",
        dot: false,
    },
    Partition {
        num: 9,
        name: "VENDOR_TEST_PARTITION",
        dot: false,
    },
    Partition {
        num: 10,
        name: "VENDOR_HASHES_MANUF_PARTITION",
        dot: false,
    },
    Partition {
        num: 11,
        name: "VENDOR_HASHES_PROD_PARTITION",
        dot: false,
    },
    Partition {
        num: 12,
        name: "VENDOR_REVOCATIONS_PROD_PARTITION",
        dot: false,
    },
    Partition {
        num: 13,
        name: "VENDOR_SECRET_PROD_PARTITION",
        dot: false,
    },
    Partition {
        num: 14,
        name: "VENDOR_NON_SECRET_PROD_PARTITION",
        dot: false,
    },
    Partition {
        num: 15,
        name: "CPTRA_SS_LOCK_HEK_PROD_0",
        dot: false,
    },
    Partition {
        num: 16,
        name: "CPTRA_SS_LOCK_HEK_PROD_1",
        dot: false,
    },
    Partition {
        num: 17,
        name: "CPTRA_SS_LOCK_HEK_PROD_2",
        dot: false,
    },
    Partition {
        num: 18,
        name: "CPTRA_SS_LOCK_HEK_PROD_3",
        dot: false,
    },
    Partition {
        num: 19,
        name: "CPTRA_SS_LOCK_HEK_PROD_4",
        dot: false,
    },
    Partition {
        num: 20,
        name: "CPTRA_SS_LOCK_HEK_PROD_5",
        dot: false,
    },
    Partition {
        num: 21,
        name: "CPTRA_SS_LOCK_HEK_PROD_6",
        dot: false,
    },
    Partition {
        num: 22,
        name: "CPTRA_SS_LOCK_HEK_PROD_7",
        dot: false,
    },
    Partition {
        num: 23,
        name: "LIFE_CYCLE",
        dot: false,
    },
];
pub const SECRET_VENDOR_FUSES: &[Fuse] = &[Fuse {
    name: "vendor_recovery_pk_hash",
    size: Bytes(48),
}];
pub const NON_SECRET_VENDOR_FUSES: &[Fuse] = &[
    Fuse {
        name: "dot_initialized",
        size: Bytes(1),
    },
    Fuse {
        name: "dot_fuse_array",
        size: Bytes(32),
    },
    Fuse {
        name: "perma_hek_en",
        size: Bytes(1),
    },
];
pub const FUSE_FIELDS: &[FuseField] = &[
    FuseField {
        name: "dot_initialized",
        bits: Bits(1),
    },
    FuseField {
        name: "dot_fuse_array",
        bits: Bits(256),
    },
    FuseField {
        name: "perma_hek_en",
        bits: Bits(1),
    },
    FuseField {
        name: "vendor_recovery_pk_hash",
        bits: Bits(384),
    },
];
/// Lookup table mapping (partition_num, entry_num) to OTP addresses and layout.
/// Only populated for fields that have a partition assignment in fuses.hjson.
pub const FUSE_ENTRY_TABLE: &[FuseEntryInfo] = &[
    FuseEntryInfo {
        partition_num: 14,
        entry_num: 0,
        byte_offset: 0xaa8,
        byte_size: 32,
        name: "dot_initialized",
        layout: FuseLayoutType::LinearMajorityVote {
            bits: 1,
            duplication: 3,
        },
    },
    FuseEntryInfo {
        partition_num: 14,
        entry_num: 1,
        byte_offset: 0xac8,
        byte_size: 32,
        name: "dot_fuse_array",
        layout: FuseLayoutType::OneHot { bits: 256 },
    },
    FuseEntryInfo {
        partition_num: 14,
        entry_num: 2,
        byte_offset: 0xae8,
        byte_size: 32,
        name: "perma_hek_en",
        layout: FuseLayoutType::LinearMajorityVote {
            bits: 1,
            duplication: 3,
        },
    },
    FuseEntryInfo {
        partition_num: 13,
        entry_num: 0,
        byte_offset: 0x898,
        byte_size: 32,
        name: "vendor_recovery_pk_hash",
        layout: FuseLayoutType::Single { bits: 384 },
    },
];
/// Fuse entry for `dot_initialized`.
pub const DOT_INITIALIZED: &FuseEntryInfo = &FUSE_ENTRY_TABLE[0];
/// Fuse entry for `dot_fuse_array`.
pub const DOT_FUSE_ARRAY: &FuseEntryInfo = &FUSE_ENTRY_TABLE[1];
/// Fuse entry for `perma_hek_en`.
pub const PERMA_HEK_EN: &FuseEntryInfo = &FUSE_ENTRY_TABLE[2];
/// Fuse entry for `vendor_recovery_pk_hash`.
pub const VENDOR_RECOVERY_PK_HASH: &FuseEntryInfo = &FUSE_ENTRY_TABLE[3];
/// OTP item entry for `CPTRA_SS_MANUF_DEBUG_UNLOCK_TOKEN`.
pub const OTP_CPTRA_SS_MANUF_DEBUG_UNLOCK_TOKEN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 0,
    entry_num: 0,
    byte_offset: 0x0,
    byte_size: 64,
    name: "CPTRA_SS_MANUF_DEBUG_UNLOCK_TOKEN",
    layout: FuseLayoutType::Single { bits: 512 },
};
/// OTP item entry for `CPTRA_CORE_ANTI_ROLLBACK_DISABLE`.
pub const OTP_CPTRA_CORE_ANTI_ROLLBACK_DISABLE: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 0,
    byte_offset: 0xf8,
    byte_size: 4,
    name: "CPTRA_CORE_ANTI_ROLLBACK_DISABLE",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_IDEVID_CERT_IDEVID_ATTR`.
pub const OTP_CPTRA_CORE_IDEVID_CERT_IDEVID_ATTR: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 1,
    byte_offset: 0xfc,
    byte_size: 96,
    name: "CPTRA_CORE_IDEVID_CERT_IDEVID_ATTR",
    layout: FuseLayoutType::Single { bits: 768 },
};
/// OTP item entry for `SOC_SPECIFIC_IDEVID_CERTIFICATE`.
pub const OTP_SOC_SPECIFIC_IDEVID_CERTIFICATE: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 2,
    byte_offset: 0x15c,
    byte_size: 4,
    name: "SOC_SPECIFIC_IDEVID_CERTIFICATE",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_IDEVID_MANUF_HSM_IDENTIFIER`.
pub const OTP_CPTRA_CORE_IDEVID_MANUF_HSM_IDENTIFIER: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 3,
    byte_offset: 0x160,
    byte_size: 16,
    name: "CPTRA_CORE_IDEVID_MANUF_HSM_IDENTIFIER",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_CORE_SOC_STEPPING_ID`.
pub const OTP_CPTRA_CORE_SOC_STEPPING_ID: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 4,
    byte_offset: 0x170,
    byte_size: 4,
    name: "CPTRA_CORE_SOC_STEPPING_ID",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_0`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 5,
    byte_offset: 0x174,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_0",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_1`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 6,
    byte_offset: 0x1a4,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_1",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_2`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 7,
    byte_offset: 0x1d4,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_2",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_3`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 8,
    byte_offset: 0x204,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_3",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_4`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 9,
    byte_offset: 0x234,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_4",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_5`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 10,
    byte_offset: 0x264,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_5",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_6`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 11,
    byte_offset: 0x294,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_6",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_7`.
pub const OTP_CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 6,
    entry_num: 12,
    byte_offset: 0x2c4,
    byte_size: 48,
    name: "CPTRA_SS_PROD_DEBUG_UNLOCK_PKS_7",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_1`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 0,
    byte_offset: 0x300,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_1",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_2`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 1,
    byte_offset: 0x310,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_2",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_3`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 2,
    byte_offset: 0x320,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_3",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_4`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 3,
    byte_offset: 0x330,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_4",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_5`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 4,
    byte_offset: 0x340,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_5",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_6`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 5,
    byte_offset: 0x350,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_6",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_UNLOCK_TOKEN_7`.
pub const OTP_CPTRA_SS_TEST_UNLOCK_TOKEN_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 6,
    byte_offset: 0x360,
    byte_size: 16,
    name: "CPTRA_SS_TEST_UNLOCK_TOKEN_7",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_TEST_EXIT_TO_MANUF_TOKEN`.
pub const OTP_CPTRA_SS_TEST_EXIT_TO_MANUF_TOKEN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 7,
    byte_offset: 0x370,
    byte_size: 16,
    name: "CPTRA_SS_TEST_EXIT_TO_MANUF_TOKEN",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_MANUF_TO_PROD_TOKEN`.
pub const OTP_CPTRA_SS_MANUF_TO_PROD_TOKEN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 8,
    byte_offset: 0x380,
    byte_size: 16,
    name: "CPTRA_SS_MANUF_TO_PROD_TOKEN",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_PROD_TO_PROD_END_TOKEN`.
pub const OTP_CPTRA_SS_PROD_TO_PROD_END_TOKEN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 9,
    byte_offset: 0x390,
    byte_size: 16,
    name: "CPTRA_SS_PROD_TO_PROD_END_TOKEN",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_RMA_TOKEN`.
pub const OTP_CPTRA_SS_RMA_TOKEN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 7,
    entry_num: 10,
    byte_offset: 0x3a0,
    byte_size: 16,
    name: "CPTRA_SS_RMA_TOKEN",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_CORE_FMC_KEY_MANIFEST_SVN`.
pub const OTP_CPTRA_CORE_FMC_KEY_MANIFEST_SVN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 8,
    entry_num: 0,
    byte_offset: 0x3b8,
    byte_size: 4,
    name: "CPTRA_CORE_FMC_KEY_MANIFEST_SVN",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_RUNTIME_SVN`.
pub const OTP_CPTRA_CORE_RUNTIME_SVN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 8,
    entry_num: 1,
    byte_offset: 0x3bc,
    byte_size: 16,
    name: "CPTRA_CORE_RUNTIME_SVN",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_CORE_SOC_MANIFEST_SVN`.
pub const OTP_CPTRA_CORE_SOC_MANIFEST_SVN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 8,
    entry_num: 2,
    byte_offset: 0x3cc,
    byte_size: 16,
    name: "CPTRA_CORE_SOC_MANIFEST_SVN",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_CORE_SOC_MANIFEST_MAX_SVN`.
pub const OTP_CPTRA_CORE_SOC_MANIFEST_MAX_SVN: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 8,
    entry_num: 3,
    byte_offset: 0x3dc,
    byte_size: 4,
    name: "CPTRA_CORE_SOC_MANIFEST_MAX_SVN",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `VENDOR_TEST`.
pub const OTP_VENDOR_TEST: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 9,
    entry_num: 0,
    byte_offset: 0x3e0,
    byte_size: 32,
    name: "VENDOR_TEST",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_0`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 10,
    entry_num: 0,
    byte_offset: 0x420,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_0",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_0`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 10,
    entry_num: 1,
    byte_offset: 0x450,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_0",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_SS_OWNER_PK_HASH`.
pub const OTP_CPTRA_SS_OWNER_PK_HASH: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 0,
    byte_offset: 0x460,
    byte_size: 48,
    name: "CPTRA_SS_OWNER_PK_HASH",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_OWNER_PQC_KEY_TYPE`.
pub const OTP_CPTRA_SS_OWNER_PQC_KEY_TYPE: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 1,
    byte_offset: 0x490,
    byte_size: 4,
    name: "CPTRA_SS_OWNER_PQC_KEY_TYPE",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_SS_OWNER_PK_HASH_VALID`.
pub const OTP_CPTRA_SS_OWNER_PK_HASH_VALID: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 2,
    byte_offset: 0x494,
    byte_size: 4,
    name: "CPTRA_SS_OWNER_PK_HASH_VALID",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_1`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 3,
    byte_offset: 0x498,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_1",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_1`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 4,
    byte_offset: 0x4c8,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_1",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_2`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 5,
    byte_offset: 0x4cc,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_2",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_2`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 6,
    byte_offset: 0x4fc,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_2",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_3`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 7,
    byte_offset: 0x500,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_3",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_3`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 8,
    byte_offset: 0x530,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_3",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_4`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 9,
    byte_offset: 0x534,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_4",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_4`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 10,
    byte_offset: 0x564,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_4",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_5`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 11,
    byte_offset: 0x568,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_5",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_5`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 12,
    byte_offset: 0x598,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_5",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_6`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 13,
    byte_offset: 0x59c,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_6",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_6`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 14,
    byte_offset: 0x5cc,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_6",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_7`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 15,
    byte_offset: 0x5d0,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_7",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_7`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 16,
    byte_offset: 0x600,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_7",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_8`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 17,
    byte_offset: 0x604,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_8",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_8`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 18,
    byte_offset: 0x634,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_8",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_9`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 19,
    byte_offset: 0x638,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_9",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_9`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 20,
    byte_offset: 0x668,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_9",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_10`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 21,
    byte_offset: 0x66c,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_10",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_10`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 22,
    byte_offset: 0x69c,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_10",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_11`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 23,
    byte_offset: 0x6a0,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_11",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_11`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 24,
    byte_offset: 0x6d0,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_11",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_12`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 25,
    byte_offset: 0x6d4,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_12",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_12`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 26,
    byte_offset: 0x704,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_12",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_13`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 27,
    byte_offset: 0x708,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_13",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_13`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 28,
    byte_offset: 0x738,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_13",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_14`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 29,
    byte_offset: 0x73c,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_14",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_14`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 30,
    byte_offset: 0x76c,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_14",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_15`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 31,
    byte_offset: 0x770,
    byte_size: 48,
    name: "CPTRA_CORE_VENDOR_PK_HASH_15",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_CORE_PQC_KEY_TYPE_15`.
pub const OTP_CPTRA_CORE_PQC_KEY_TYPE_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 32,
    byte_offset: 0x7a0,
    byte_size: 4,
    name: "CPTRA_CORE_PQC_KEY_TYPE_15",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_VENDOR_PK_HASH_VALID`.
pub const OTP_CPTRA_CORE_VENDOR_PK_HASH_VALID: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 11,
    entry_num: 33,
    byte_offset: 0x7a4,
    byte_size: 16,
    name: "CPTRA_CORE_VENDOR_PK_HASH_VALID",
    layout: FuseLayoutType::Single { bits: 128 },
};
/// OTP item entry for `CPTRA_SS_OWNER_ECC_REVOCATION`.
pub const OTP_CPTRA_SS_OWNER_ECC_REVOCATION: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 0,
    byte_offset: 0x7c0,
    byte_size: 4,
    name: "CPTRA_SS_OWNER_ECC_REVOCATION",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_SS_OWNER_LMS_REVOCATION`.
pub const OTP_CPTRA_SS_OWNER_LMS_REVOCATION: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 1,
    byte_offset: 0x7c4,
    byte_size: 4,
    name: "CPTRA_SS_OWNER_LMS_REVOCATION",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_SS_OWNER_MLDSA_REVOCATION`.
pub const OTP_CPTRA_SS_OWNER_MLDSA_REVOCATION: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 2,
    byte_offset: 0x7c8,
    byte_size: 4,
    name: "CPTRA_SS_OWNER_MLDSA_REVOCATION",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_0`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 3,
    byte_offset: 0x7cc,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_0",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_0`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 4,
    byte_offset: 0x7d0,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_0",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_0`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 5,
    byte_offset: 0x7d4,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_0",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_1`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 6,
    byte_offset: 0x7d8,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_1",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_1`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 7,
    byte_offset: 0x7dc,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_1",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_1`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 8,
    byte_offset: 0x7e0,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_1",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_2`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 9,
    byte_offset: 0x7e4,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_2",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_2`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 10,
    byte_offset: 0x7e8,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_2",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_2`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 11,
    byte_offset: 0x7ec,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_2",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_3`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 12,
    byte_offset: 0x7f0,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_3",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_3`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 13,
    byte_offset: 0x7f4,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_3",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_3`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 14,
    byte_offset: 0x7f8,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_3",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_4`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 15,
    byte_offset: 0x7fc,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_4",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_4`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 16,
    byte_offset: 0x800,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_4",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_4`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 17,
    byte_offset: 0x804,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_4",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_5`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 18,
    byte_offset: 0x808,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_5",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_5`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 19,
    byte_offset: 0x80c,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_5",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_5`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 20,
    byte_offset: 0x810,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_5",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_6`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 21,
    byte_offset: 0x814,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_6",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_6`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 22,
    byte_offset: 0x818,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_6",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_6`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 23,
    byte_offset: 0x81c,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_6",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_7`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 24,
    byte_offset: 0x820,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_7",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_7`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 25,
    byte_offset: 0x824,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_7",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_7`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 26,
    byte_offset: 0x828,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_7",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_8`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 27,
    byte_offset: 0x82c,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_8",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_8`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 28,
    byte_offset: 0x830,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_8",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_8`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 29,
    byte_offset: 0x834,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_8",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_9`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 30,
    byte_offset: 0x838,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_9",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_9`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 31,
    byte_offset: 0x83c,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_9",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_9`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 32,
    byte_offset: 0x840,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_9",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_10`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 33,
    byte_offset: 0x844,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_10",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_10`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 34,
    byte_offset: 0x848,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_10",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_10`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 35,
    byte_offset: 0x84c,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_10",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_11`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 36,
    byte_offset: 0x850,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_11",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_11`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 37,
    byte_offset: 0x854,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_11",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_11`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 38,
    byte_offset: 0x858,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_11",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_12`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 39,
    byte_offset: 0x85c,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_12",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_12`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 40,
    byte_offset: 0x860,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_12",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_12`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 41,
    byte_offset: 0x864,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_12",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_13`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 42,
    byte_offset: 0x868,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_13",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_13`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 43,
    byte_offset: 0x86c,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_13",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_13`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 44,
    byte_offset: 0x870,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_13",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_14`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 45,
    byte_offset: 0x874,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_14",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_14`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 46,
    byte_offset: 0x878,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_14",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_14`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 47,
    byte_offset: 0x87c,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_14",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_ECC_REVOCATION_15`.
pub const OTP_CPTRA_CORE_ECC_REVOCATION_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 48,
    byte_offset: 0x880,
    byte_size: 4,
    name: "CPTRA_CORE_ECC_REVOCATION_15",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_LMS_REVOCATION_15`.
pub const OTP_CPTRA_CORE_LMS_REVOCATION_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 49,
    byte_offset: 0x884,
    byte_size: 4,
    name: "CPTRA_CORE_LMS_REVOCATION_15",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `CPTRA_CORE_MLDSA_REVOCATION_15`.
pub const OTP_CPTRA_CORE_MLDSA_REVOCATION_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 12,
    entry_num: 50,
    byte_offset: 0x888,
    byte_size: 4,
    name: "CPTRA_CORE_MLDSA_REVOCATION_15",
    layout: FuseLayoutType::Single { bits: 32 },
};
/// OTP item entry for `vendor_recovery_pk_hash`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 0,
    byte_offset: 0x898,
    byte_size: 32,
    name: "vendor_recovery_pk_hash",
    layout: FuseLayoutType::Single { bits: 384 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_1`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 1,
    byte_offset: 0x8b8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_1",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_2`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 2,
    byte_offset: 0x8d8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_2",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_3`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 3,
    byte_offset: 0x8f8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_3",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_4`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 4,
    byte_offset: 0x918,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_4",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_5`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 5,
    byte_offset: 0x938,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_5",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_6`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 6,
    byte_offset: 0x958,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_6",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_7`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 7,
    byte_offset: 0x978,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_7",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_8`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 8,
    byte_offset: 0x998,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_8",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_9`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 9,
    byte_offset: 0x9b8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_9",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_10`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 10,
    byte_offset: 0x9d8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_10",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_11`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 11,
    byte_offset: 0x9f8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_11",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_12`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 12,
    byte_offset: 0xa18,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_12",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_13`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 13,
    byte_offset: 0xa38,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_13",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_14`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 14,
    byte_offset: 0xa58,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_14",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_15`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 13,
    entry_num: 15,
    byte_offset: 0xa78,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_SECRET_FUSE_15",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `dot_initialized`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_0: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 0,
    byte_offset: 0xaa8,
    byte_size: 32,
    name: "dot_initialized",
    layout: FuseLayoutType::LinearMajorityVote {
        bits: 1,
        duplication: 3,
    },
};
/// OTP item entry for `dot_fuse_array`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_1: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 1,
    byte_offset: 0xac8,
    byte_size: 32,
    name: "dot_fuse_array",
    layout: FuseLayoutType::OneHot { bits: 256 },
};
/// OTP item entry for `perma_hek_en`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_2: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 2,
    byte_offset: 0xae8,
    byte_size: 32,
    name: "perma_hek_en",
    layout: FuseLayoutType::LinearMajorityVote {
        bits: 1,
        duplication: 3,
    },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_3`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_3: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 3,
    byte_offset: 0xb08,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_3",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_4`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_4: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 4,
    byte_offset: 0xb28,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_4",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_5`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_5: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 5,
    byte_offset: 0xb48,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_5",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_6`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_6: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 6,
    byte_offset: 0xb68,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_6",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_7`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_7: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 7,
    byte_offset: 0xb88,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_7",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_8`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_8: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 8,
    byte_offset: 0xba8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_8",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_9`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_9: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 9,
    byte_offset: 0xbc8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_9",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_10`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_10: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 10,
    byte_offset: 0xbe8,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_10",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_11`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_11: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 11,
    byte_offset: 0xc08,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_11",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_12`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_12: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 12,
    byte_offset: 0xc28,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_12",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_13`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_13: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 13,
    byte_offset: 0xc48,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_13",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_14`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_14: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 14,
    byte_offset: 0xc68,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_14",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_15`.
pub const OTP_CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_15: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 14,
    entry_num: 15,
    byte_offset: 0xc88,
    byte_size: 32,
    name: "CPTRA_SS_VENDOR_SPECIFIC_NON_SECRET_FUSE_15",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_0_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_0_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 15,
    entry_num: 0,
    byte_offset: 0xcb0,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_0_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_1_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_1_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 16,
    entry_num: 0,
    byte_offset: 0xce0,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_1_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_2_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_2_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 17,
    entry_num: 0,
    byte_offset: 0xd10,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_2_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_3_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_3_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 18,
    entry_num: 0,
    byte_offset: 0xd40,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_3_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_4_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_4_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 19,
    entry_num: 0,
    byte_offset: 0xd70,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_4_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_5_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_5_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 20,
    entry_num: 0,
    byte_offset: 0xda0,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_5_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_6_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_6_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 21,
    entry_num: 0,
    byte_offset: 0xdd0,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_6_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
/// OTP item entry for `CPTRA_SS_LOCK_HEK_PROD_7_RATCHET_SEED`.
pub const OTP_CPTRA_SS_LOCK_HEK_PROD_7_RATCHET_SEED: &FuseEntryInfo = &FuseEntryInfo {
    partition_num: 22,
    entry_num: 0,
    byte_offset: 0xe00,
    byte_size: 32,
    name: "CPTRA_SS_LOCK_HEK_PROD_7_RATCHET_SEED",
    layout: FuseLayoutType::Single { bits: 256 },
};
