// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with otp_ctrl_mmap.hjson and fuses.hjson
/// Describes an OTP partition with its location, size, and digest properties.
#[derive(Debug, Clone, Copy)]
pub struct OtpPartitionInfo {
    /// Partition name.
    pub name: &'static str,
    /// Byte offset of the partition within the OTP address space.
    pub byte_offset: usize,
    /// Total byte size of the partition (including the digest field if present).
    pub byte_size: usize,
    /// Whether this partition supports a software-computed digest.
    pub sw_digest: bool,
    /// Whether this partition has a hardware-computed digest.
    pub hw_digest: bool,
    /// Byte offset of the 8-byte digest field within OTP (if sw_digest or hw_digest is true).
    pub digest_offset: Option<usize>,
}
/// All OTP partitions with their locations and digest properties.
pub const OTP_PARTITIONS: &[OtpPartitionInfo] = &[
    OtpPartitionInfo {
        name: "sw_test_unlock_partition",
        byte_offset: 0x0,
        byte_size: 0x48,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0x40),
    },
    OtpPartitionInfo {
        name: "secret_manuf_partition",
        byte_offset: 0x48,
        byte_size: 0x48,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0x88),
    },
    OtpPartitionInfo {
        name: "secret_prod_partition_0",
        byte_offset: 0x90,
        byte_size: 0x10,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0x98),
    },
    OtpPartitionInfo {
        name: "secret_prod_partition_1",
        byte_offset: 0xa0,
        byte_size: 0x10,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0xa8),
    },
    OtpPartitionInfo {
        name: "secret_prod_partition_2",
        byte_offset: 0xb0,
        byte_size: 0x10,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0xb8),
    },
    OtpPartitionInfo {
        name: "secret_prod_partition_3",
        byte_offset: 0xc0,
        byte_size: 0x10,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0xc8),
    },
    OtpPartitionInfo {
        name: "sw_manuf_partition",
        byte_offset: 0xd0,
        byte_size: 0x208,
        sw_digest: true,
        hw_digest: false,
        digest_offset: Some(0x2d0),
    },
    OtpPartitionInfo {
        name: "secret_lc_transition_partition",
        byte_offset: 0x2d8,
        byte_size: 0xb8,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0x388),
    },
    OtpPartitionInfo {
        name: "svn_partition",
        byte_offset: 0x390,
        byte_size: 0x28,
        sw_digest: false,
        hw_digest: false,
        digest_offset: None,
    },
    OtpPartitionInfo {
        name: "vendor_test_partition",
        byte_offset: 0x3b8,
        byte_size: 0x40,
        sw_digest: true,
        hw_digest: false,
        digest_offset: Some(0x3f0),
    },
    OtpPartitionInfo {
        name: "vendor_hashes_manuf_partition",
        byte_offset: 0x3f8,
        byte_size: 0x40,
        sw_digest: true,
        hw_digest: false,
        digest_offset: Some(0x430),
    },
    OtpPartitionInfo {
        name: "vendor_hashes_prod_partition",
        byte_offset: 0x438,
        byte_size: 0x360,
        sw_digest: true,
        hw_digest: false,
        digest_offset: Some(0x790),
    },
    OtpPartitionInfo {
        name: "vendor_revocations_prod_partition",
        byte_offset: 0x798,
        byte_size: 0xd8,
        sw_digest: true,
        hw_digest: false,
        digest_offset: Some(0x868),
    },
    OtpPartitionInfo {
        name: "vendor_secret_prod_partition",
        byte_offset: 0x870,
        byte_size: 0x208,
        sw_digest: false,
        hw_digest: true,
        digest_offset: Some(0xa70),
    },
    OtpPartitionInfo {
        name: "vendor_non_secret_prod_partition",
        byte_offset: 0xa78,
        byte_size: 0x208,
        sw_digest: true,
        hw_digest: false,
        digest_offset: Some(0xc78),
    },
    OtpPartitionInfo {
        name: "life_cycle",
        byte_offset: 0xc80,
        byte_size: 0x58,
        sw_digest: false,
        hw_digest: false,
        digest_offset: None,
    },
];
pub const SW_TEST_UNLOCK_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[0];
pub const SECRET_MANUF_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[1];
pub const SECRET_PROD_PARTITION_0: &OtpPartitionInfo = &OTP_PARTITIONS[2];
pub const SECRET_PROD_PARTITION_1: &OtpPartitionInfo = &OTP_PARTITIONS[3];
pub const SECRET_PROD_PARTITION_2: &OtpPartitionInfo = &OTP_PARTITIONS[4];
pub const SECRET_PROD_PARTITION_3: &OtpPartitionInfo = &OTP_PARTITIONS[5];
pub const SW_MANUF_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[6];
pub const SECRET_LC_TRANSITION_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[7];
pub const SVN_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[8];
pub const VENDOR_TEST_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[9];
pub const VENDOR_HASHES_MANUF_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[10];
pub const VENDOR_HASHES_PROD_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[11];
pub const VENDOR_REVOCATIONS_PROD_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[12];
pub const VENDOR_SECRET_PROD_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[13];
pub const VENDOR_NON_SECRET_PROD_PARTITION: &OtpPartitionInfo = &OTP_PARTITIONS[14];
pub const LIFE_CYCLE: &OtpPartitionInfo = &OTP_PARTITIONS[15];
pub const SW_TEST_UNLOCK_PARTITION_BYTE_OFFSET: usize = 0x0;
pub const SW_TEST_UNLOCK_PARTITION_BYTE_SIZE: usize = 0x48;
pub const SECRET_MANUF_PARTITION_BYTE_OFFSET: usize = 0x48;
pub const SECRET_MANUF_PARTITION_BYTE_SIZE: usize = 0x48;
pub const SECRET_PROD_PARTITION_0_BYTE_OFFSET: usize = 0x90;
pub const SECRET_PROD_PARTITION_0_BYTE_SIZE: usize = 0x10;
pub const SECRET_PROD_PARTITION_1_BYTE_OFFSET: usize = 0xa0;
pub const SECRET_PROD_PARTITION_1_BYTE_SIZE: usize = 0x10;
pub const SECRET_PROD_PARTITION_2_BYTE_OFFSET: usize = 0xb0;
pub const SECRET_PROD_PARTITION_2_BYTE_SIZE: usize = 0x10;
pub const SECRET_PROD_PARTITION_3_BYTE_OFFSET: usize = 0xc0;
pub const SECRET_PROD_PARTITION_3_BYTE_SIZE: usize = 0x10;
pub const SW_MANUF_PARTITION_BYTE_OFFSET: usize = 0xd0;
pub const SW_MANUF_PARTITION_BYTE_SIZE: usize = 0x208;
pub const SECRET_LC_TRANSITION_PARTITION_BYTE_OFFSET: usize = 0x2d8;
pub const SECRET_LC_TRANSITION_PARTITION_BYTE_SIZE: usize = 0xb8;
pub const SVN_PARTITION_BYTE_OFFSET: usize = 0x390;
pub const SVN_PARTITION_BYTE_SIZE: usize = 0x28;
pub const VENDOR_TEST_PARTITION_BYTE_OFFSET: usize = 0x3b8;
pub const VENDOR_TEST_PARTITION_BYTE_SIZE: usize = 0x40;
pub const VENDOR_HASHES_MANUF_PARTITION_BYTE_OFFSET: usize = 0x3f8;
pub const VENDOR_HASHES_MANUF_PARTITION_BYTE_SIZE: usize = 0x40;
pub const VENDOR_HASHES_PROD_PARTITION_BYTE_OFFSET: usize = 0x438;
pub const VENDOR_HASHES_PROD_PARTITION_BYTE_SIZE: usize = 0x360;
pub const VENDOR_REVOCATIONS_PROD_PARTITION_BYTE_OFFSET: usize = 0x798;
pub const VENDOR_REVOCATIONS_PROD_PARTITION_BYTE_SIZE: usize = 0xd8;
pub const VENDOR_SECRET_PROD_PARTITION_BYTE_OFFSET: usize = 0x870;
pub const VENDOR_SECRET_PROD_PARTITION_BYTE_SIZE: usize = 0x208;
pub const VENDOR_NON_SECRET_PROD_PARTITION_BYTE_OFFSET: usize = 0xa78;
pub const VENDOR_NON_SECRET_PROD_PARTITION_BYTE_SIZE: usize = 0x208;
pub const LIFE_CYCLE_BYTE_OFFSET: usize = 0xc80;
pub const LIFE_CYCLE_BYTE_SIZE: usize = 0x58;

// Licensed under the Apache-2.0 license.
// Autogenerated file from fuses.hjson. Do not modify this file.

#[derive(Debug, Clone)]
pub struct Partition {
    pub num: usize,
    pub name: &'static str,
    pub dot: bool,
}
#[derive(Debug, Clone, Copy)]
pub struct Bytes(pub usize);
#[derive(Debug, Clone, Copy)]
pub struct Bits(pub usize);
#[derive(Debug, Clone)]
pub struct Fuse {
    pub name: &'static str,
    pub size: Bytes,
}
#[derive(Debug, Clone)]
pub struct FuseField {
    pub name: &'static str,
    pub bits: Bits,
}
/// Layout type for interpreting raw fuse bits.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FuseLayoutType {
    Single { bits: u32 },
    OneHot { bits: u32 },
    LinearMajorityVote { bits: u32, duplication: u32 },
    OneHotLinearMajorityVote { bits: u32, duplication: u32 },
    WordMajorityVote { bits: u32, duplication: u32 },
}
/// Entry in the fuse lookup table mapping (partition, entry) to OTP location and layout.
#[derive(Debug, Clone)]
pub struct FuseEntryInfo {
    /// Partition number (index into OTP partitions)
    pub partition_num: usize,
    /// Entry number within the partition
    pub entry_num: usize,
    /// Byte offset from start of OTP
    pub byte_offset: usize,
    /// Size in bytes of the raw fuse storage
    pub byte_size: usize,
    /// Field name
    pub name: &'static str,
    /// Layout for interpreting the raw bits
    pub layout: FuseLayoutType,
}
pub const PARTITIONS: &[Partition] = &[];
pub const SECRET_VENDOR_FUSES: &[Fuse] = &[Fuse {
    name: "vendor_recovery_pk_hash",
    size: Bytes(48),
}];
pub const NON_SECRET_VENDOR_FUSES: &[Fuse] = &[
    Fuse {
        name: "dot_initialized",
        size: Bytes(1),
    },
    Fuse {
        name: "dot_fuse_array",
        size: Bytes(32),
    },
];
pub const FUSE_FIELDS: &[FuseField] = &[
    FuseField {
        name: "dot_initialized",
        bits: Bits(1),
    },
    FuseField {
        name: "dot_fuse_array",
        bits: Bits(256),
    },
    FuseField {
        name: "vendor_recovery_pk_hash",
        bits: Bits(384),
    },
];
/// Lookup table mapping (partition_num, entry_num) to OTP addresses and layout.
/// Only populated for fields that have a partition assignment in fuses.hjson.
pub const FUSE_ENTRY_TABLE: &[FuseEntryInfo] = &[
    FuseEntryInfo {
        partition_num: 14,
        entry_num: 0,
        byte_offset: 0xa78,
        byte_size: 32,
        name: "dot_initialized",
        layout: FuseLayoutType::LinearMajorityVote {
            bits: 1,
            duplication: 3,
        },
    },
    FuseEntryInfo {
        partition_num: 14,
        entry_num: 1,
        byte_offset: 0xa98,
        byte_size: 32,
        name: "dot_fuse_array",
        layout: FuseLayoutType::OneHot { bits: 256 },
    },
    FuseEntryInfo {
        partition_num: 13,
        entry_num: 0,
        byte_offset: 0x870,
        byte_size: 32,
        name: "vendor_recovery_pk_hash",
        layout: FuseLayoutType::Single { bits: 384 },
    },
];
/// Fuse entry for `dot_initialized`.
pub const DOT_INITIALIZED: &FuseEntryInfo = &FUSE_ENTRY_TABLE[0];
/// Fuse entry for `dot_fuse_array`.
pub const DOT_FUSE_ARRAY: &FuseEntryInfo = &FUSE_ENTRY_TABLE[1];
/// Fuse entry for `vendor_recovery_pk_hash`.
pub const VENDOR_RECOVERY_PK_HASH: &FuseEntryInfo = &FUSE_ENTRY_TABLE[2];
