// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 2b7c4bf60cde3101c4287d31213164d1767ce33e
//
#![recursion_limit = "2048"]
#![no_std]
pub mod axicdma;
pub mod defines;
pub mod doe_mbox;
pub mod el2_pic_ctrl;
pub mod fuses;
pub mod i3c;
pub mod lc_ctrl;
pub mod mbox;
pub mod mci;
pub mod otp_ctrl;
pub mod primary_flash_ctrl;
pub mod secondary_flash_ctrl;
pub mod sha512_acc;
pub mod soc;
