// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 54772ea48fe4fc718b5e4f773dca2603b020bf96
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
