// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at b3fdf7e8c6d73fd49d44d2772636922bd0148f06
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
