// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 3350c70a296bf897abe8c02e5ec0da69cc83ee16
//
pub const SECONDARY_FLASH_CTRL_ADDR: u32 = 0x2000_8800;
