// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 153965c8ac848854f21c4f8efe73eb5584dbda33
//
pub const USBDEV_ADDR: u32 = 0x900_0000;
pub mod bits {
    //! Types that represent individual registers (bitfields).
    use tock_registers::register_bitfields;
    register_bitfields! {
        u32,
            pub AlertTest [
                /// Write 1 to trigger one alert event of this kind.
                FatalFault OFFSET(0) NUMBITS(1) [],
            ],
            pub IntrEnable [
                /// Enable interrupt when !!INTR_STATE.pkt_received is set.
                PktReceived OFFSET(0) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.pkt_sent is set.
                PktSent OFFSET(1) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.disconnected is set.
                Disconnected OFFSET(2) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.host_lost is set.
                HostLost OFFSET(3) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.link_reset is set.
                LinkReset OFFSET(4) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.link_suspend is set.
                LinkSuspend OFFSET(5) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.link_resume is set.
                LinkResume OFFSET(6) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.av_out_empty is set.
                AvOutEmpty OFFSET(7) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.rx_full is set.
                RxFull OFFSET(8) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.av_overflow is set.
                AvOverflow OFFSET(9) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.link_in_err is set.
                LinkInErr OFFSET(10) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.rx_crc_err is set.
                RxCrcErr OFFSET(11) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.rx_pid_err is set.
                RxPidErr OFFSET(12) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.rx_bitstuff_err is set.
                RxBitstuffErr OFFSET(13) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.frame is set.
                Frame OFFSET(14) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.powered is set.
                Powered OFFSET(15) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.link_out_err is set.
                LinkOutErr OFFSET(16) NUMBITS(1) [],
                /// Enable interrupt when !!INTR_STATE.av_setup_empty is set.
                AvSetupEmpty OFFSET(17) NUMBITS(1) [],
            ],
            pub IntrState [
                /// Raised if a packet was received using an OUT or SETUP transaction.
                /// This interrupt is directly tied to whether the RX FIFO is empty, so it should be cleared only after handling the FIFO entry.
                PktReceived OFFSET(0) NUMBITS(1) [],
                /// Raised if a packet was sent as part of an IN transaction.
                /// This interrupt is directly tied to whether a sent packet has not been acknowledged in the !!in_sent register.
                /// It should be cleared only after clearing all bits in the !!in_sent register.
                PktSent OFFSET(1) NUMBITS(1) [],
                /// Raised if VBUS is lost or the pullup is disabled, thus the link is disconnected.
                Disconnected OFFSET(2) NUMBITS(1) [],
                /// Raised if link is active but SOF was not received from host for 4.096 ms. The SOF should be every 1 ms.
                HostLost OFFSET(3) NUMBITS(1) [],
                /// Raised if the link is at SE0 longer than 3 us indicating a link reset (host asserts for min 10 ms, device can react after 2.5 us).
                LinkReset OFFSET(4) NUMBITS(1) [],
                /// Raised if the line has signaled J for longer than 3ms and is therefore in suspend state.
                LinkSuspend OFFSET(5) NUMBITS(1) [],
                /// Raised when the link becomes active again after being suspended.
                LinkResume OFFSET(6) NUMBITS(1) [],
                /// Raised when the Available OUT Buffer FIFO is empty and the device interface is enabled.
                /// This interrupt is directly tied to the FIFO status, so the Available OUT Buffer FIFO must be provided with a free buffer before the interrupt can be cleared.
                AvOutEmpty OFFSET(7) NUMBITS(1) [],
                /// Raised when the RX FIFO is full and the device interface is enabled.
                /// This interrupt is directly tied to the FIFO status, so the RX FIFO must have an entry removed before the interrupt is cleared.
                /// If the condition is not cleared, the interrupt can re-assert.
                RxFull OFFSET(8) NUMBITS(1) [],
                /// Raised if a write was done to either the Available OUT Buffer FIFO or the Available SETUP Buffer FIFO when the FIFO was full.
                AvOverflow OFFSET(9) NUMBITS(1) [],
                /// Raised if a packet to an IN endpoint started to be received but was
                /// then dropped due to an error. After transmitting the IN payload,
                /// the USB device expects a valid ACK handshake packet. This error is
                /// raised if either the packet or CRC is invalid, leading to a NAK instead,
                /// or if a different token was received.
                LinkInErr OFFSET(10) NUMBITS(1) [],
                /// Raised if a CRC error occurred on a received packet.
                RxCrcErr OFFSET(11) NUMBITS(1) [],
                /// Raised if an invalid Packet IDentifier (PID) was received.
                RxPidErr OFFSET(12) NUMBITS(1) [],
                /// Raised if an invalid bitstuffing was received.
                RxBitstuffErr OFFSET(13) NUMBITS(1) [],
                /// Raised when the USB frame number is updated with a valid SOF.
                Frame OFFSET(14) NUMBITS(1) [],
                /// Raised if VBUS is applied.
                Powered OFFSET(15) NUMBITS(1) [],
                /// Raised if a packet to an OUT endpoint started to be received but was then dropped due to an error.
                /// This error is raised if the data toggle, token, packet and/or CRC are invalid, or if the appropriate Available OUT Buffer FIFO is empty and/or the Received Buffer FIFO is full when a packet should have been received.
                /// Attempting to perform an OUT transaction to an endpoint that is stalled, i.e. its control bit in `out_stall` is set, will also cause this error to be raised.
                LinkOutErr OFFSET(16) NUMBITS(1) [],
                /// Raised when the Available SETUP Buffer FIFO is empty and the device interface is enabled.
                /// This interrupt is directly tied to the FIFO status, so the Available SETUP Buffer FIFO must be provided with a free buffer before the interrupt can be cleared.
                AvSetupEmpty OFFSET(17) NUMBITS(1) [],
            ],
            pub IntrTest [
                /// Write 1 to force !!INTR_STATE.pkt_received to 1.
                PktReceived OFFSET(0) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.pkt_sent to 1.
                PktSent OFFSET(1) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.disconnected to 1.
                Disconnected OFFSET(2) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.host_lost to 1.
                HostLost OFFSET(3) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.link_reset to 1.
                LinkReset OFFSET(4) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.link_suspend to 1.
                LinkSuspend OFFSET(5) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.link_resume to 1.
                LinkResume OFFSET(6) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.av_out_empty to 1.
                AvOutEmpty OFFSET(7) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.rx_full to 1.
                RxFull OFFSET(8) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.av_overflow to 1.
                AvOverflow OFFSET(9) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.link_in_err to 1.
                LinkInErr OFFSET(10) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.rx_crc_err to 1.
                RxCrcErr OFFSET(11) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.rx_pid_err to 1.
                RxPidErr OFFSET(12) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.rx_bitstuff_err to 1.
                RxBitstuffErr OFFSET(13) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.frame to 1.
                Frame OFFSET(14) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.powered to 1.
                Powered OFFSET(15) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.link_out_err to 1.
                LinkOutErr OFFSET(16) NUMBITS(1) [],
                /// Write 1 to force !!INTR_STATE.av_setup_empty to 1.
                AvSetupEmpty OFFSET(17) NUMBITS(1) [],
            ],
            pub Avoutbuffer [
                /// This field contains the buffer ID being passed to the USB receive engine.
                ///
                /// If the Available OUT Buffer FIFO is full, any write operations are discarded.
                Buffer OFFSET(0) NUMBITS(5) [],
            ],
            pub Avsetupbuffer [
                /// This field contains the buffer ID being passed to the USB receive engine.
                ///
                /// If the Available SETUP Buffer FIFO is full, any write operations are discarded.
                Buffer OFFSET(0) NUMBITS(5) [],
            ],
            pub Configin0 [
                /// The buffer ID containing the data to send when an IN transaction is received on the endpoint.
                Buffer0 OFFSET(0) NUMBITS(5) [],
                /// The number of bytes to send from the buffer.
                ///
                /// If this is 0 then a CRC only packet is sent.
                ///
                /// If this is greater than 64 then 64 bytes are sent.
                Size0 OFFSET(8) NUMBITS(7) [],
                /// This bit indicates that the buffer is in the process of being collected by the
                /// host. It becomes set upon the first attempt by the host to collect a buffer from
                /// this endpoint when the rdy bit was set.
                ///
                /// It is cleared when the packet has been collected successfully or the pending
                /// transaction has been canceled by the hardware through detection of a
                /// link reset or receipt of a SETUP packet.
                Sending0 OFFSET(29) NUMBITS(1) [],
                /// This bit indicates a pending transaction was canceled by the hardware.
                ///
                /// The bit is set when the rdy bit is cleared by hardware because of a
                /// SETUP packet being received or a link reset being detected.
                ///
                /// The bit remains set until cleared by being written with a 1.
                Pend0 OFFSET(30) NUMBITS(1) [],
                /// This bit should be set to indicate the buffer is ready for sending.
                /// It will be cleared when the ACK is received indicating the host has accepted the data.
                ///
                /// This bit will also be cleared if an enabled SETUP transaction is received on the endpoint.
                /// This allows use of the IN channel for transfer of SETUP information.
                /// The original buffer must be resubmitted after the SETUP sequence is complete.
                /// A link reset also clears the bit.
                /// In either of the cases where the hardware cancels the transaction it will also set the pend bit.
                Rdy0 OFFSET(31) NUMBITS(1) [],
            ],
            pub CountErrors [
                /// Number of events counted.
                Count OFFSET(0) NUMBITS(8) [],
                /// Number of Invalid PIDs detected on packets from the host. Invalid PIDs may
                /// indicate very unreliable communication and/or a substantial frequency mismatch
                /// between the host and the device.
                PidInvalid OFFSET(27) NUMBITS(1) [],
                /// Number of SETUP/OUT packets that were ignored, dropped or NAKed because a
                /// Bit Stuffing error was detected.
                Bitstuff OFFSET(28) NUMBITS(1) [],
                /// Count SETUP/OUT DATA packets that were ignored, dropped or NAKed because a
                /// CRC16 error was detected.
                Crc16 OFFSET(29) NUMBITS(1) [],
                /// Count CRC5 errors detected on token packets sent by the host. CRC5 errors on
                /// token packets received from the host indicate very unreliable communication and
                /// possibly a substantial frequency mismatch between the host and the device.
                Crc5 OFFSET(30) NUMBITS(1) [],
                /// Write 1 to reset the counter.
                Rst OFFSET(31) NUMBITS(1) [],
            ],
            pub CountIn [
                /// Number of events counted.
                Count OFFSET(0) NUMBITS(8) [],
                /// Count the IN transactions that were attempted when there was no packet available
                /// in the corresponding 'configin' register(s). This is not necessarily an error
                /// condition, and the counter primarily offers some visibility into when the IN
                /// traffic is underusing the available bus bandwidth.
                /// It is of particular utility to Isochronous IN endpoints.
                Nodata OFFSET(13) NUMBITS(1) [],
                /// Count the IN transactions rejected by the host responding with a NAK handshake.
                Nak OFFSET(14) NUMBITS(1) [],
                /// Count the IN transactions for which the USB host did not respond with a handshake,
                /// and the transactions timed out. This indicates that the host did not receive it
                /// and decode it as a valid packet, suggesting that communication is unreliable.
                ///
                /// Isochronous IN transactions are excluded from this count because there is no
                /// handshake response to Isochronous packet transfers.
                Timeout OFFSET(15) NUMBITS(1) [],
                /// Set of endpoints for which this counter is enabled.
                Endpoints OFFSET(16) NUMBITS(12) [],
                /// Write 1 to reset the counter.
                Rst OFFSET(31) NUMBITS(1) [],
            ],
            pub CountNodataIn [
                /// Number of IN transactions that were attempted when there was no packet available
                /// in the corresponding 'configin' register(s).
                Count OFFSET(0) NUMBITS(8) [],
                /// Set of endpoints for which this counter is enabled.
                Endpoints OFFSET(16) NUMBITS(12) [],
                /// Write 1 to reset the counter.
                Rst OFFSET(31) NUMBITS(1) [],
            ],
            pub CountOut [
                /// Number of events counted.
                Count OFFSET(0) NUMBITS(8) [],
                /// Count the OUT transactions for which the USB device acknowledged the OUT packet
                /// and dropped it internally, which is the correct response to a packet transmitted
                /// with an incorrect Data Toggle.
                ///
                /// The expectation is that this packet is a retry of the previous packet transmission
                /// and that the handshake response was not received intact by the USB host, indicating
                /// unreliable communications.
                ///
                /// Other causes of Data Toggle synchronization failure may result in data loss.
                DatatogOut OFFSET(12) NUMBITS(1) [],
                /// Count the SETUP/OUT packets ignored, dropped or NAKed because the RX FIFO was full.
                /// SETUP packets have been ignored, Isochronous OUT packets have been dropped, and
                /// non-Isochronous OUT packets have been NAKed.
                DropRx OFFSET(13) NUMBITS(1) [],
                /// Count the OUT packets that could not be accepted because there was no buffer in the
                /// Av OUT FIFO. Non-Isochronous OUT packets have been NAKed.
                /// Isochronous OUT packets were ignored.
                DropAvout OFFSET(14) NUMBITS(1) [],
                /// Count the SETUP packets that were ignored because there was no buffer in the
                /// Av SETUP FIFO.
                IgnAvsetup OFFSET(15) NUMBITS(1) [],
                /// Set of OUT endpoints for which this counter is enabled.
                Endpoints OFFSET(16) NUMBITS(12) [],
                /// Write 1 to reset the counter.
                Rst OFFSET(31) NUMBITS(1) [],
            ],
            pub EpInEnable [
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable0 OFFSET(0) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable1 OFFSET(1) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable2 OFFSET(2) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable3 OFFSET(3) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable4 OFFSET(4) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable5 OFFSET(5) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable6 OFFSET(6) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable7 OFFSET(7) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable8 OFFSET(8) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable9 OFFSET(9) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable10 OFFSET(10) NUMBITS(1) [],
                /// This bit must be set to enable upstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear then any IN packets sent to the endpoint will be ignored.
                Enable11 OFFSET(11) NUMBITS(1) [],
            ],
            pub EpOutEnable [
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable0 OFFSET(0) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable1 OFFSET(1) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable2 OFFSET(2) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable3 OFFSET(3) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable4 OFFSET(4) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable5 OFFSET(5) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable6 OFFSET(6) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable7 OFFSET(7) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable8 OFFSET(8) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable9 OFFSET(9) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable10 OFFSET(10) NUMBITS(1) [],
                /// This bit must be set to enable downstream transactions to be received on the endpoint and elicit responses.
                /// If the bit is clear, any SETUP or OUT packets sent to the endpoint will be ignored.
                Enable11 OFFSET(11) NUMBITS(1) [],
            ],
            pub FifoCtrl [
                /// Software reset of the Available OUT Buffer FIFO. This must be used only when the USB device
                /// is not connected to the USB.
                AvoutRst OFFSET(0) NUMBITS(1) [],
                /// Software reset of the Available SETUP Buffer FIFO. This must be used only when the USB device
                /// is not connected to the USB.
                AvsetupRst OFFSET(1) NUMBITS(1) [],
                /// Software reset the of Rx Buffer FIFO. This must be used only when the USB device is not
                /// connected to the USB.
                RxRst OFFSET(2) NUMBITS(1) [],
            ],
            pub InDataToggle [
                /// Reading returns the current state of the IN endpoint Data Toggle flags.
                /// Writing sets the Data Toggle flag for each endpoint if the corresponding mask bit
                /// in the upper half of this register is set.
                Status OFFSET(0) NUMBITS(12) [],
                /// Reads as zero.
                /// When writing, a set bit will cause the Data Toggle flag of the corresponding
                /// IN endpoint to be updated. A clear bit will leave the flag for the corresponding
                /// endpoint unchanged.
                Mask OFFSET(16) NUMBITS(12) [],
            ],
            pub InIso [
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso0 OFFSET(0) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso1 OFFSET(1) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso2 OFFSET(2) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso3 OFFSET(3) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso4 OFFSET(4) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso5 OFFSET(5) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso6 OFFSET(6) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso7 OFFSET(7) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso8 OFFSET(8) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso9 OFFSET(9) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso10 OFFSET(10) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be expected for an IN transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso11 OFFSET(11) NUMBITS(1) [],
            ],
            pub InSent [
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent0 OFFSET(0) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent1 OFFSET(1) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent2 OFFSET(2) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent3 OFFSET(3) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent4 OFFSET(4) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent5 OFFSET(5) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent6 OFFSET(6) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent7 OFFSET(7) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent8 OFFSET(8) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent9 OFFSET(9) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent10 OFFSET(10) NUMBITS(1) [],
                /// This bit will be set when the ACK is received from
                /// the host to indicate successful packet delivery
                /// as part of an IN transaction.
                Sent11 OFFSET(11) NUMBITS(1) [],
            ],
            pub InStall [
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint0 OFFSET(0) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint1 OFFSET(1) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint2 OFFSET(2) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint3 OFFSET(3) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint4 OFFSET(4) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint5 OFFSET(5) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint6 OFFSET(6) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint7 OFFSET(7) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint8 OFFSET(8) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint9 OFFSET(9) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint10 OFFSET(10) NUMBITS(1) [],
                /// If this bit is set then an IN transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint11 OFFSET(11) NUMBITS(1) [],
            ],
            pub OutDataToggle [
                /// Reading returns the current state of the OUT endpoint Data Toggle flags.
                /// Writing sets the Data Toggle flag for each endpoint if the corresponding mask bit
                /// in the upper half of this register is set.
                Status OFFSET(0) NUMBITS(12) [],
                /// Reads as zero.
                /// When writing, a set bit will cause the Data Toggle flag of the corresponding
                /// OUT endpoint to be updated. A clear bit will leave the flag for the corresponding
                /// endpoint unchanged.
                Mask OFFSET(16) NUMBITS(12) [],
            ],
            pub OutIso [
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso0 OFFSET(0) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso1 OFFSET(1) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso2 OFFSET(2) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso3 OFFSET(3) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso4 OFFSET(4) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso5 OFFSET(5) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso6 OFFSET(6) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso7 OFFSET(7) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso8 OFFSET(8) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso9 OFFSET(9) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso10 OFFSET(10) NUMBITS(1) [],
                /// If this bit is set then the endpoint will be treated as an isochronous endpoint.
                /// No handshake packet will be sent for an OUT transaction.
                /// Note that if a rxenable_setup is set for this endpoint's number, this bit will not take effect.
                /// Control endpoint configuration trumps isochronous endpoint configuration.
                Iso11 OFFSET(11) NUMBITS(1) [],
            ],
            pub OutStall [
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint0 OFFSET(0) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint1 OFFSET(1) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint2 OFFSET(2) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint3 OFFSET(3) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint4 OFFSET(4) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint5 OFFSET(5) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint6 OFFSET(6) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint7 OFFSET(7) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint8 OFFSET(8) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint9 OFFSET(9) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint10 OFFSET(10) NUMBITS(1) [],
                /// If this bit is set then an OUT transaction to this endpoint will elicit a STALL handshake, when a non-isochronous endpoint is enabled.
                /// If the configuration has both STALL and NAK enabled, the STALL handshake will take priority.
                ///
                /// Note that SETUP transactions are always either accepted or ignored.
                /// For endpoints that accept SETUP transactions, a SETUP packet will clear the STALL flag on endpoints for both the IN and OUT directions.
                Endpoint11 OFFSET(11) NUMBITS(1) [],
            ],
            pub PhyConfig [
                /// Detect received K and J symbols from the usb_rx_d signal, which must be driven from an external differential receiver.
                /// If 1, make use of the usb_rx_d input.
                /// If 0, the usb_rx_d input is ignored and the usb_rx_dp and usb_rx_dn pair are used to detect K and J (useful for some environments, but will be unlikely to pass full USB compliance).
                /// Regardless of the state of this field usb_rx_dp and usb_rx_dn are always used to detect SE0.
                /// This bit also feeds the rx_enable pin, activating the receiver when the device is not suspended.
                UseDiffRcvr OFFSET(0) NUMBITS(1) [],
                /// If 1, select the d and se0 TX interface.
                /// If 0, select the dp and dn TX interface.
                /// This directly controls the output pin of the same name.
                /// It is intended to be used to enable the use of a variety of external transceivers, to select an encoding that matches the transceiver.
                TxUseDSe0 OFFSET(1) NUMBITS(1) [],
                /// Recognize a single SE0 bit as an end of packet, otherwise two successive bits are required.
                EopSingleBit OFFSET(2) NUMBITS(1) [],
                /// Flip the D+/D- pins.
                /// Particularly useful if D+/D- are mapped to SBU1/SBU2 pins of USB-C.
                Pinflip OFFSET(5) NUMBITS(1) [],
                /// 0: Enable reference signal generation for clock synchronization, 1: disable it by forcing the associated signals to zero.
                UsbRefDisable OFFSET(6) NUMBITS(1) [],
                /// Disable (0) or enable (1) oscillator test mode.
                /// If enabled, the device constantly transmits a J/K pattern, which is useful for testing the USB clock.
                /// Note that while in oscillator test mode, the device no longer receives SOFs and consequently does not generate the reference signal for clock synchronization.
                /// The clock might drift off.
                TxOscTestMode OFFSET(7) NUMBITS(1) [],
            ],
            pub PhyPinsDrive [
                /// USB transmit D+ output, used with dn_o.
                DpO OFFSET(0) NUMBITS(1) [],
                /// USB transmit D- output, used with dp_o.
                DnO OFFSET(1) NUMBITS(1) [],
                /// USB transmit data output, encoding K and J when se0_o is 0.
                DO OFFSET(2) NUMBITS(1) [],
                /// USB single-ended zero output.
                Se0O OFFSET(3) NUMBITS(1) [],
                /// USB OE output.
                OeO OFFSET(4) NUMBITS(1) [],
                /// Enable differential receiver.
                RxEnableO OFFSET(5) NUMBITS(1) [],
                /// USB D+ pullup enable output.
                DpPullupEnO OFFSET(6) NUMBITS(1) [],
                /// USB D- pullup enable output.
                DnPullupEnO OFFSET(7) NUMBITS(1) [],
                /// 0: Outputs are controlled by the hardware block.
                /// 1: Outputs are controlled with this register.
                En OFFSET(16) NUMBITS(1) [],
            ],
            pub PhyPinsSense [
                /// USB D+ input.
                RxDpI OFFSET(0) NUMBITS(1) [],
                /// USB D- input.
                RxDnI OFFSET(1) NUMBITS(1) [],
                /// USB data input from an external differential receiver, if available.
                RxDI OFFSET(2) NUMBITS(1) [],
                /// USB transmit D+ output (readback).
                TxDpO OFFSET(8) NUMBITS(1) [],
                /// USB transmit D- output (readback).
                TxDnO OFFSET(9) NUMBITS(1) [],
                /// USB transmit data value (readback).
                TxDO OFFSET(10) NUMBITS(1) [],
                /// USB single-ended zero output (readback).
                TxSe0O OFFSET(11) NUMBITS(1) [],
                /// USB OE output (readback).
                TxOeO OFFSET(12) NUMBITS(1) [],
                /// USB power sense signal.
                PwrSense OFFSET(16) NUMBITS(1) [],
            ],
            pub RxenableOut [
                /// This bit must be set to enable OUT transactions to be received on the endpoint.
                /// If the bit is clear but the endpoint is enabled, then an OUT request will receive a NAK in response.
                /// If set_nak_out for this endpoint is set, hardware will clear this bit whenever an OUT transaction is received on this endpoint.
                /// Software must set this bit again to receive the next OUT transaction.
                /// Until that happens, hardware will continue to NAK any OUT transactions to this endpoint.
                Out OFFSET(0) NUMBITS(12) [],
                /// When writing to this register, only those 'out' bits with a corresponding 'preserve' bit of 0 are updated.
                /// The 'preserve' field should therefore normally be set to all '1s', except for those bits that the software wishes to modify.
                /// This conditional update facility avoids a race with the hardware when it is clearing the 'out' bit for another enabled endpoint.
                Preserve OFFSET(16) NUMBITS(12) [],
            ],
            pub RxenableSetup [
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup0 OFFSET(0) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup1 OFFSET(1) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup2 OFFSET(2) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup3 OFFSET(3) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup4 OFFSET(4) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup5 OFFSET(5) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup6 OFFSET(6) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup7 OFFSET(7) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup8 OFFSET(8) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup9 OFFSET(9) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup10 OFFSET(10) NUMBITS(1) [],
                /// This bit must be set to enable SETUP transactions to be
                /// received on the endpoint. If the bit is clear then a
                /// SETUP packet will be ignored. The bit should be set for
                /// control endpoints (and only control endpoints).
                Setup11 OFFSET(11) NUMBITS(1) [],
            ],
            pub Rxfifo [
                /// This field contains the buffer ID that data was received into.
                /// On read the buffer ID is popped from the Received Buffer FIFO and returned to software.
                Buffer OFFSET(0) NUMBITS(5) [],
                /// This field contains the data length in bytes of the packet written to the buffer.
                Size OFFSET(8) NUMBITS(7) [],
                /// This bit indicates if the received transaction is of type SETUP (1) or OUT (0).
                Setup OFFSET(19) NUMBITS(1) [],
                /// This field contains the endpoint ID to which the packet was directed.
                Ep OFFSET(20) NUMBITS(4) [],
            ],
            pub SetNakOut [
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable0 OFFSET(0) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable1 OFFSET(1) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable2 OFFSET(2) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable3 OFFSET(3) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable4 OFFSET(4) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable5 OFFSET(5) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable6 OFFSET(6) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable7 OFFSET(7) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable8 OFFSET(8) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable9 OFFSET(9) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable10 OFFSET(10) NUMBITS(1) [],
                /// When this bit is set, hardware will clear this endpoint's rxenable_out bit whenever an OUT transaction is received on this endpoint.
                /// This bit should not be changed while the endpoint is active.
                Enable11 OFFSET(11) NUMBITS(1) [],
            ],
            pub Usbctrl [
                /// Set to connect the USB interface (i.e. assert the pullup).
                Enable OFFSET(0) NUMBITS(1) [],
                /// Write a 1 to this bit to instruct usbdev to jump to the LinkResuming state.
                /// The write will only have an effect when the device is in the LinkPowered state.
                /// Its intention is to handle a resume-from-suspend event after the IP has been powered down.
                ResumeLinkActive OFFSET(1) NUMBITS(1) [],
                /// Device address set by host (this should be copied from
                /// the Set Device ID SETUP packet).
                ///
                /// This will be zeroed by the hardware when the link resets.
                DeviceAddress OFFSET(16) NUMBITS(7) [],
            ],
            pub Usbstat [
                /// Frame index received from host. On an active link, this will increment every millisecond.
                Frame OFFSET(0) NUMBITS(11) [],
                /// Start of frame not received from host for 4.096 ms and the line is active.
                HostLost OFFSET(11) NUMBITS(1) [],
                /// State of USB link, decoded from line.
                LinkState OFFSET(12) NUMBITS(3) [],
                /// Reflects the state of the sense pin.
                /// 1 indicates that the host is providing VBUS.
                /// Note that this bit always shows the state of the actual pin and is unaffected by the direct pin driving in phy_pins_drive.
                Sense OFFSET(15) NUMBITS(1) [],
                /// Number of buffers in the Available OUT Buffer FIFO.
                ///
                /// These buffers are available for receiving OUT DATA packets.
                AvOutDepth OFFSET(16) NUMBITS(4) [],
                /// Number of buffers in the Available SETUP Buffer FIFO.
                ///
                /// These buffers are available for receiving SETUP DATA packets.
                AvSetupDepth OFFSET(20) NUMBITS(3) [],
                /// Available OUT Buffer FIFO is full.
                AvOutFull OFFSET(23) NUMBITS(1) [],
                /// Number of buffers in the Received Buffer FIFO.
                ///
                /// These buffers have packets that have been received and
                /// should be popped from the FIFO and processed.
                RxDepth OFFSET(24) NUMBITS(4) [],
                /// Available SETUP Buffer FIFO is full.
                AvSetupFull OFFSET(30) NUMBITS(1) [],
                /// Received Buffer FIFO is empty.
                RxEmpty OFFSET(31) NUMBITS(1) [],
            ],
            pub WakeControl [
                /// Suspend request to the wake detection module.
                ///
                /// Trigger the wake detection module to begin monitoring for wake-from-suspend events.
                /// When written with a 1, the wake detection module will activate.
                /// Activation may not happen immediately, and its status can be verified by checking wake_events.module_active.
                SuspendReq OFFSET(0) NUMBITS(1) [],
                /// Wake acknowledgement.
                ///
                /// Signal to the wake detection module that it may release control of the pull-ups back to the main block and return to an inactive state.
                /// The release back to normal state may not happen immediately.
                /// The status can be confirmed via wake_events.module_active.
                ///
                /// Note that this bit can also be used without powering down, such as when usbdev detects resume signaling before transitions to low power states have begun.
                WakeAck OFFSET(1) NUMBITS(1) [],
            ],
            pub WakeEvents [
                /// USB aon wake module is active, monitoring events and controlling the pull-ups.
                ModuleActive OFFSET(0) NUMBITS(1) [],
                /// USB aon wake module detected VBUS was interrupted while monitoring events.
                Disconnected OFFSET(8) NUMBITS(1) [],
                /// USB aon wake module detected a bus reset while monitoring events.
                BusReset OFFSET(9) NUMBITS(1) [],
                /// USB aon wake module detected a non-idle bus while monitoring events.
                BusNotIdle OFFSET(10) NUMBITS(1) [],
            ],
    }
}
pub mod regs {
    //! Types that represent registers.
    use tock_registers::register_structs;
    register_structs! {
        pub Usbdev {
            (0x0 => pub intr_state: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::IntrState::Register>),
            (0x4 => pub intr_enable: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::IntrEnable::Register>),
            (0x8 => pub intr_test: tock_registers::registers::WriteOnly<u32, crate::usbdev::bits::IntrTest::Register>),
            (0xc => pub alert_test: tock_registers::registers::WriteOnly<u32, crate::usbdev::bits::AlertTest::Register>),
            (0x10 => pub usbctrl: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::Usbctrl::Register>),
            (0x14 => pub ep_out_enable: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::EpOutEnable::Register>),
            (0x18 => pub ep_in_enable: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::EpInEnable::Register>),
            (0x1c => pub usbstat: tock_registers::registers::ReadOnly<u32, crate::usbdev::bits::Usbstat::Register>),
            (0x20 => pub avoutbuffer: tock_registers::registers::WriteOnly<u32, crate::usbdev::bits::Avoutbuffer::Register>),
            (0x24 => pub avsetupbuffer: tock_registers::registers::WriteOnly<u32, crate::usbdev::bits::Avsetupbuffer::Register>),
            (0x28 => pub rxfifo: tock_registers::registers::ReadOnly<u32, crate::usbdev::bits::Rxfifo::Register>),
            (0x2c => pub rxenable_setup: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::RxenableSetup::Register>),
            (0x30 => pub rxenable_out: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::RxenableOut::Register>),
            (0x34 => pub set_nak_out: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::SetNakOut::Register>),
            (0x38 => pub in_sent: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::InSent::Register>),
            (0x3c => pub out_stall: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::OutStall::Register>),
            (0x40 => pub in_stall: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::InStall::Register>),
            (0x44 => pub configin_0: [tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::Configin0::Register>; 12]),
            (0x74 => pub out_iso: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::OutIso::Register>),
            (0x78 => pub in_iso: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::InIso::Register>),
            (0x7c => pub out_data_toggle: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::OutDataToggle::Register>),
            (0x80 => pub in_data_toggle: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::InDataToggle::Register>),
            (0x84 => pub phy_pins_sense: tock_registers::registers::ReadOnly<u32, crate::usbdev::bits::PhyPinsSense::Register>),
            (0x88 => pub phy_pins_drive: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::PhyPinsDrive::Register>),
            (0x8c => pub phy_config: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::PhyConfig::Register>),
            (0x90 => pub wake_control: tock_registers::registers::WriteOnly<u32, crate::usbdev::bits::WakeControl::Register>),
            (0x94 => pub wake_events: tock_registers::registers::ReadOnly<u32, crate::usbdev::bits::WakeEvents::Register>),
            (0x98 => pub fifo_ctrl: tock_registers::registers::WriteOnly<u32, crate::usbdev::bits::FifoCtrl::Register>),
            (0x9c => pub count_out: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::CountOut::Register>),
            (0xa0 => pub count_in: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::CountIn::Register>),
            (0xa4 => pub count_nodata_in: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::CountNodataIn::Register>),
            (0xa8 => pub count_errors: tock_registers::registers::ReadWrite<u32, crate::usbdev::bits::CountErrors::Register>),
            (0xac => _reserved0),
            (0x800 => pub buffer: [tock_registers::registers::ReadWrite<u32>; 512]),
            (0x1000 => @END),
        }
    }
}
