// Licensed under the Apache-2.0 license

//! SPDM cryptographic algorithm types.
//!
//! Algorithm bitmaps are typed: each family has its own `Unaligned`
//! newtype generated by [`def_flag_set_le!`] so handler code uses
//! named constants (e.g. `AeadAlgos::AES_256_GCM`) instead of magic
//! bit positions.

use zerocopy::{
    little_endian::{U16, U32},
    FromBytes, Immutable, IntoBytes, KnownLayout, Unaligned,
};

use crate::flag_macros::{def_flag_set_le, def_flag_set_u8};
use crate::{ReqRespCode, ResponseBody, WireError, WireWriter};

// ---- typed algorithm bit-flag types ----------------------------------------

def_flag_set_u8! {
  /// MeasurementSpecification.
    pub struct MeasSpec {
        DMTF = 1 << 0,
    }
}

def_flag_set_u8! {
  /// OtherParamsSupport / OtherParamsSel (SPDM the corresponding table
  /// byte 7) — opaque-data-format negotiation introduced in v1.2.
    pub struct OtherParamSupport {
        OPAQUE_DATA_FMT1 = 1 << 1,
    /// SPDM 1.3 MultiKeyConn negotiation.
        MULTI_KEY_CONN = 1 << 4,
    }
}

def_flag_set_le! {
  /// MeasurementHashAlgo.
    pub struct MeasHashAlgos(U32: u32) {
        RAW_BIT = 1 << 0,
        SHA_256 = 1 << 1,
        SHA_384 = 1 << 2,
        SHA_512 = 1 << 3,
        SHA3_256 = 1 << 4,
        SHA3_384 = 1 << 5,
        SHA3_512 = 1 << 6,
        SM3_256 = 1 << 7,
    }
}

def_flag_set_le! {
  /// BaseAsymAlgo / BaseAsymSel.
    pub struct AsymAlgos(U32: u32) {
        RSASSA_2048 = 1 << 0,
        RSAPSS_2048 = 1 << 1,
        RSASSA_3072 = 1 << 2,
        RSAPSS_3072 = 1 << 3,
        ECDSA_ECC_NIST_P256 = 1 << 4,
        RSASSA_4096 = 1 << 5,
        RSAPSS_4096 = 1 << 6,
        ECDSA_ECC_NIST_P384 = 1 << 7,
        ECDSA_ECC_NIST_P521 = 1 << 8,
        SM2_ECC_SM2_P256 = 1 << 9,
        EDDSA_ED25519 = 1 << 10,
        EDDSA_ED448 = 1 << 11,
    }
}

def_flag_set_le! {
  /// BaseHashAlgo / BaseHashSel.
    pub struct HashAlgos(U32: u32) {
        SHA_256 = 1 << 0,
        SHA_384 = 1 << 1,
        SHA_512 = 1 << 2,
        SHA3_256 = 1 << 3,
        SHA3_384 = 1 << 4,
        SHA3_512 = 1 << 5,
        SM3_256 = 1 << 6,
    }
}

def_flag_set_le! {
  /// DHE.AlgSupported.
    pub struct DheAlgos(U16: u16) {
        FFDHE_2048 = 1 << 0,
        FFDHE_3072 = 1 << 1,
        FFDHE_4096 = 1 << 2,
        SECP_256_R1 = 1 << 3,
        SECP_384_R1 = 1 << 4,
        SECP_521_R1 = 1 << 5,
        SM2_P256 = 1 << 6,
    }
}

def_flag_set_le! {
  /// AEAD.AlgSupported.
    pub struct AeadAlgos(U16: u16) {
        AES_128_GCM = 1 << 0,
        AES_256_GCM = 1 << 1,
        CHACHA20_POLY1305 = 1 << 2,
        AEAD_SM4_GCM = 1 << 3,
    }
}

def_flag_set_le! {
  /// KeySchedule.AlgSupported.
    pub struct KeyScheduleAlgos(U16: u16) {
        SPDM = 1 << 0,
    }
}

// ---- AlgType discriminants -------------------------------------------------

/// `AlgType` byte values for AlgStruct entries.
pub mod alg_type {
    pub const DHE: u8 = 0x02;
    pub const AEAD: u8 = 0x03;
    pub const REQ_BASE_ASYM: u8 = 0x04;
    pub const KEY_SCHEDULE: u8 = 0x05;
}

// ---- NEGOTIATE_ALGORITHMS request wire types -------------------------------

/// Fixed 30-byte prefix of the NEGOTIATE_ALGORITHMS request body
///. Followed by zero or more 4-byte
/// extended-asym entries, then extended-hash entries, then
/// [`AlgStructEntry`] entries.
#[derive(FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Copy, Clone, Default)]
#[repr(C)]
pub struct NegotiateAlgorithmsReqBodyFixed {
    /// Param1: number of AlgStruct entries that follow.
    pub num_alg_struct: u8,
    /// Param2: Reserved (must be 0).
    pub param2: u8,
    /// Total request length in bytes (including SPDM header).
    pub length: U16,
    pub measurement_spec: MeasSpec,
    pub other_param_support: OtherParamSupport,
    pub base_asym_algo: AsymAlgos,
    pub base_hash_algo: HashAlgos,
    pub reserved1: [u8; 12],
    pub ext_asym_count: u8,
    pub ext_hash_count: u8,
    /// Byte 28: Reserved.
    pub reserved2: u8,
    /// Byte 29: MelSpecification (V1.3) / Reserved (V1.2).
    pub mel_spec_or_reserved: u8,
}

impl NegotiateAlgorithmsReqBodyFixed {
    pub const SIZE: usize = 30;
    /// Maximum total request length accepted by this responder.
    pub const MAX_REQUEST_LENGTH: u16 = 128;
}

const _: () = assert!(
    core::mem::size_of::<NegotiateAlgorithmsReqBodyFixed>()
        == NegotiateAlgorithmsReqBodyFixed::SIZE
);

// ---- ALGORITHMS response wire types ----------------------------------------

/// Fixed-size prefix of the ALGORITHMS response body. Followed by
/// zero or more 4-byte AlgStruct entries.
#[derive(FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Copy, Clone, Default)]
#[repr(C)]
pub struct AlgorithmsRspBodyFixed {
    pub num_alg_struct: u8,
    pub param2: u8,
    pub length: U16,
    pub measurement_spec_sel: MeasSpec,
    pub other_param_support: OtherParamSupport,
    pub meas_hash_algo: MeasHashAlgos,
    pub base_asym_sel: AsymAlgos,
    pub base_hash_sel: HashAlgos,
    pub reserved3: [u8; 12],
    pub ext_asym_sel_count: u8,
    pub ext_hash_sel_count: u8,
    pub reserved4: [u8; 2],
}

impl AlgorithmsRspBodyFixed {
    pub const SIZE: usize = 34;
}

const _: () =
    assert!(core::mem::size_of::<AlgorithmsRspBodyFixed>() == AlgorithmsRspBodyFixed::SIZE);

/// 4-byte AlgStruct entry.
#[derive(FromBytes, IntoBytes, KnownLayout, Immutable, Unaligned, Copy, Clone, Default)]
#[repr(C)]
pub struct AlgStructEntry {
    /// One of [`alg_type`] constants.
    pub alg_type: u8,
    /// `FixedAlgCount[3:0] | ExtAlgCount[7:4]`. We always emit
    /// `FixedAlgCount = 2` (one 16-bit AlgSupported bitmap, no
    /// external algs).
    pub alg_count_etc: u8,
    pub alg_supported: U16,
}

impl AlgStructEntry {
    pub const SIZE: usize = 4;
    pub const FIXED_ALG_COUNT_ETC: u8 = 0x20;

    /// Helper for a DHE selection.
    pub fn dhe(algos: DheAlgos) -> Self {
        Self {
            alg_type: alg_type::DHE,
            alg_count_etc: Self::FIXED_ALG_COUNT_ETC,
            alg_supported: U16::new(algos.into_bits()),
        }
    }
    /// Helper for an AEAD selection.
    pub fn aead(algos: AeadAlgos) -> Self {
        Self {
            alg_type: alg_type::AEAD,
            alg_count_etc: Self::FIXED_ALG_COUNT_ETC,
            alg_supported: U16::new(algos.into_bits()),
        }
    }
    /// Helper for a KeySchedule selection.
    pub fn key_schedule(algos: KeyScheduleAlgos) -> Self {
        Self {
            alg_type: alg_type::KEY_SCHEDULE,
            alg_count_etc: Self::FIXED_ALG_COUNT_ETC,
            alg_supported: U16::new(algos.into_bits()),
        }
    }
}

const _: () = assert!(core::mem::size_of::<AlgStructEntry>() == AlgStructEntry::SIZE);

/// Maximum AlgStruct entries the responder advertises (DHE, AEAD,
/// ReqBaseAsymAlg, KeySchedule).
pub const MAX_ALG_STRUCT_ENTRIES: usize = 4;

/// Builder for an ALGORITHMS response (v1.2+).
pub struct AlgorithmsRsp {
    pub measurement_spec_sel: MeasSpec,
    pub other_param_support: OtherParamSupport,
    pub meas_hash_algo: MeasHashAlgos,
    pub base_asym_sel: AsymAlgos,
    pub base_hash_sel: HashAlgos,
    /// AlgStruct entries to advertise; `None` slots are skipped.
    pub alg_structs: [Option<AlgStructEntry>; MAX_ALG_STRUCT_ENTRIES],
}

impl AlgorithmsRsp {
    fn num_alg_struct(&self) -> u8 {
        self.alg_structs.iter().filter(|x| x.is_some()).count() as u8
    }
}

impl ResponseBody for AlgorithmsRsp {
    const RESPONSE_CODE: ReqRespCode = ReqRespCode::ALGORITHMS;

    fn body_size(&self) -> usize {
        AlgorithmsRspBodyFixed::SIZE + (self.num_alg_struct() as usize) * AlgStructEntry::SIZE
    }

    fn encode_body(&self, w: &mut WireWriter<'_>) -> Result<(), WireError> {
        let num = self.num_alg_struct();
        let length = (crate::SpdmMsgHdrPdu::SIZE + self.body_size()) as u16;
        w.write(&AlgorithmsRspBodyFixed {
            num_alg_struct: num,
            param2: 0,
            length: U16::new(length),
            measurement_spec_sel: self.measurement_spec_sel,
            other_param_support: self.other_param_support,
            meas_hash_algo: self.meas_hash_algo,
            base_asym_sel: self.base_asym_sel,
            base_hash_sel: self.base_hash_sel,
            reserved3: [0; 12],
            ext_asym_sel_count: 0,
            ext_hash_sel_count: 0,
            reserved4: [0; 2],
        })?;
        for entry in self.alg_structs.iter().flatten() {
            w.write(entry)?;
        }
        Ok(())
    }
}
