// Licensed under the Apache-2.0 license

use caliptra_mcu_error::{McuError, McuResult};
use caliptra_mcu_registers_generated::lc_ctrl;
use caliptra_mcu_romtime::{HexWord, StaticRef};
use core::fmt::Write;
use tock_registers::interfaces::{Readable, Writeable};

// TODO: fix the autogenerated offsets
// const LC_TOKENS_OFFSET: usize = fuses::SECRET_LC_TRANSITION_PARTITION_BYTE_OFFSET;
pub(crate) const LC_TOKENS_OFFSET: usize = 0x4a0;

/// Unhashed token, suitable for doing lifecycle transitions.
#[derive(Clone, Copy)]
pub struct LifecycleToken(pub [u8; 16]);

impl From<[u8; 16]> for LifecycleToken {
    fn from(value: [u8; 16]) -> Self {
        LifecycleToken(value)
    }
}

impl From<LifecycleToken> for [u8; 16] {
    fn from(value: LifecycleToken) -> Self {
        value.0
    }
}

/// Raw tokens
pub struct LifecycleRawTokens {
    pub test_unlock: [LifecycleToken; 7],
    pub manuf: LifecycleToken,
    pub manuf_to_prod: LifecycleToken,
    pub prod_to_prod_end: LifecycleToken,
    pub rma: LifecycleToken,
}

/// Hashed token, suitable for burning into the OTP.
#[derive(Clone, Copy)]
pub struct LifecycleHashedToken(pub [u8; 16]);

impl From<[u8; 16]> for LifecycleHashedToken {
    fn from(value: [u8; 16]) -> Self {
        LifecycleHashedToken(value)
    }
}

impl From<LifecycleHashedToken> for [u8; 16] {
    fn from(value: LifecycleHashedToken) -> Self {
        value.0
    }
}

/// Hashed tokens to be burned into the OTP for lifecycle transitions.
pub struct LifecycleHashedTokens {
    pub test_unlock: [LifecycleHashedToken; 7],
    pub manuf: LifecycleHashedToken,
    pub manuf_to_prod: LifecycleHashedToken,
    pub prod_to_prod_end: LifecycleHashedToken,
    pub rma: LifecycleHashedToken,
}

pub use caliptra_mcu_otp_lifecycle::LifecycleControllerState;

/// RAII guard that releases the lifecycle transition mutex on drop.
struct TransitionMutexGuard {
    registers: StaticRef<lc_ctrl::regs::LcCtrl>,
}

impl TransitionMutexGuard {
    /// Spin until the transition mutex is claimed, then return a struct
    /// that will release it on drop.
    fn claim(registers: StaticRef<lc_ctrl::regs::LcCtrl>) -> Self {
        const MULTI_TRUE: u32 = 0x96;
        while registers.claim_transition_if.get() != MULTI_TRUE {
            registers.claim_transition_if.set(MULTI_TRUE);
            let reg_value = registers.claim_transition_if.get();
            caliptra_mcu_romtime::println!(
                "[mcu-rom-lcc] Claim Mutex Register: {} (should be {})",
                HexWord(reg_value),
                HexWord(MULTI_TRUE)
            );
        }
        caliptra_mcu_romtime::println!("[mcu-rom-lcc] Mutex successfully acquired.");
        Self { registers }
    }
}

impl Drop for TransitionMutexGuard {
    fn drop(&mut self) {
        self.registers.claim_transition_if.set(0);
    }
}

pub struct Lifecycle {
    registers: StaticRef<lc_ctrl::regs::LcCtrl>,
}

impl Lifecycle {
    pub const fn new(registers: StaticRef<lc_ctrl::regs::LcCtrl>) -> Self {
        Lifecycle { registers }
    }

    pub fn init(&self) -> McuResult<()> {
        caliptra_mcu_romtime::println!("[mcu-lcc] Initializing Lifecycle controller...");
        while !self.registers.status.is_set(lc_ctrl::bits::Status::Ready) {}
        while !self
            .registers
            .status
            .is_set(lc_ctrl::bits::Status::Initialized)
        {}

        caliptra_mcu_romtime::println!(
            "[mcu-lcc] Lifecycle state: {} (count {})",
            HexWord(self.registers.lc_state.get() & 0x1f),
            self.registers.lc_transition_cnt.get()
        );

        caliptra_mcu_romtime::println!("Lifecycle controller initialization done");
        Ok(())
    }

    pub fn status(&self) -> u32 {
        self.registers.status.get()
    }

    pub fn calc_lc_state_mnemonic(state: LifecycleControllerState) -> u32 {
        let state = u8::from(state);
        let next_lc_state_5bit = (state & 0x1F) as u32;

        (next_lc_state_5bit << 25)
            | (next_lc_state_5bit << 20)
            | (next_lc_state_5bit << 15)
            | (next_lc_state_5bit << 10)
            | (next_lc_state_5bit << 5)
            | next_lc_state_5bit
    }

    pub fn transition(
        &self,
        state: LifecycleControllerState,
        token: &LifecycleToken,
    ) -> McuResult<()> {
        caliptra_mcu_romtime::println!(
            "[mcu-rom-lcc] Transitioning Lifecycle state... to {}",
            u8::from(state)
        );

        // Acquire the transition mutex (released on drop)
        let mutex = TransitionMutexGuard::claim(self.registers);
        self.transition_flow(mutex, state, token)
    }

    fn transition_flow(
        &self,
        _mutex: TransitionMutexGuard,
        state: LifecycleControllerState,
        token: &LifecycleToken,
    ) -> McuResult<()> {
        let next_lc_state_mne = Self::calc_lc_state_mnemonic(state);
        let token = u128::from_le_bytes(token.0);

        // Step 1: Set Target Lifecycle State
        caliptra_mcu_romtime::println!(
            "[mcu-rom-lcc] Setting next lifecycle state: 0x{:02x}",
            next_lc_state_mne & 0x1f
        );
        self.registers.transition_target.set(next_lc_state_mne);

        // Step 2: Write Transition Tokens
        let token_31_0 = (token & 0xFFFF_FFFF) as u32;
        let token_63_32 = ((token >> 32) & 0xFFFF_FFFF) as u32;
        let token_95_64 = ((token >> 64) & 0xFFFF_FFFF) as u32;
        let token_127_96 = ((token >> 96) & 0xFFFF_FFFF) as u32;

        caliptra_mcu_romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_31_0);
        self.registers.transition_token_0.set(token_31_0);
        caliptra_mcu_romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_63_32);
        self.registers.transition_token_1.set(token_63_32);
        caliptra_mcu_romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_95_64);
        self.registers.transition_token_2.set(token_95_64);
        caliptra_mcu_romtime::println!("[mcu-rom-lcc] Writing tokens: 0x{:08x}", token_127_96);
        self.registers.transition_token_3.set(token_127_96);

        // Step 3: Trigger the Transition Command
        caliptra_mcu_romtime::println!("[mcu-rom-lcc] Triggering transition command: 0x1",);
        self.registers.transition_cmd.set(1);

        // Step 4: Poll Status Register
        loop {
            let status = self.registers.status.extract();
            caliptra_mcu_romtime::println!(
                "[mcu-rom-lcc] Polling status register: {}",
                HexWord(status.get())
            );

            if status.is_set(lc_ctrl::bits::Status::TransitionSuccessful) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] Transition successful.");
                return Ok(());
            }
            if status.is_set(lc_ctrl::bits::Status::TransitionError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] Transition error detected.");
                return Err(McuError::ROM_LC_TRANSITION_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::TokenError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] Token error detected.");
                return Err(McuError::ROM_LC_TOKEN_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::OtpError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] OTP error detected.");
                return Err(McuError::ROM_LC_OTP_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::FlashRmaError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] FLASH RMA error detected.");
                return Err(McuError::ROM_LC_FLASH_RMA_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::TransitionCountError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] Transition count error detected.");
                return Err(McuError::ROM_LC_TRANSITION_COUNT_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::StateError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] State error detected.");
                return Err(McuError::ROM_LC_STATE_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::BusIntegError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] Bus integrity error detected.");
                return Err(McuError::ROM_LC_BUS_INTEG_ERROR);
            }
            if status.is_set(lc_ctrl::bits::Status::OtpPartitionError) {
                caliptra_mcu_romtime::println!("[mcu-rom-lcc] OTP partition error detected.");
                return Err(McuError::ROM_LC_OTP_PARTITION_ERROR);
            }
        }
    }
}
