// Licensed under the Apache-2.0 license
//
// OTP Fuse Provisioning via DAI (Direct Access Interface)
//
// Implements three fuse provisioning commands per the MC_FUSE specification:
//   MC_FUSE_READ           (0x4946_5052 / "IFPR")
//   MC_FUSE_WRITE          (0x4946_5057 / "IFPW")
//   MC_FUSE_LOCK_PARTITION (0x4946_504B / "IFPK")
//
// All OTP access goes through the DAI helpers in romtime::Otp
// (read_word, write_word, finalize_digest).

use crate::{HexWord, Otp};
use caliptra_mcu_error::McuError;
use caliptra_mcu_registers_generated::fuses;

// ---------------------------------------------------------------------------
// Partition identifiers (same numbering as the Fuse definition script)
// ---------------------------------------------------------------------------

// TODO: Replace this hand-maintained enum with autogenerated partition metadata
// from registers/generated-firmware/src/fuses.rs once #1108 merges and is
// cherry-picked to the 2.1 branch.
#[repr(u32)]
#[derive(Clone, Copy)]
enum PartitionId {
    SwTestUnlock = 0x00,
    SecretManuf = 0x01,
    SecretProd0 = 0x02,
    SecretProd1 = 0x03,
    SecretProd2 = 0x04,
    SecretProd3 = 0x05,
    SwManuf = 0x06,
    SecretLcTransition = 0x07,
    Svn = 0x08,
    VendorTest = 0x09,
    VendorHashesManuf = 0x0A,
    VendorHashesProd = 0x0B,
    VendorRevocationsProd = 0x0C,
    VendorSecretProd = 0x0D,
    VendorNonSecretProd = 0x0E,
}

impl TryFrom<u32> for PartitionId {
    type Error = McuError;

    fn try_from(v: u32) -> Result<Self, McuError> {
        match v {
            0x00 => Ok(Self::SwTestUnlock),
            0x01 => Ok(Self::SecretManuf),
            0x02 => Ok(Self::SecretProd0),
            0x03 => Ok(Self::SecretProd1),
            0x04 => Ok(Self::SecretProd2),
            0x05 => Ok(Self::SecretProd3),
            0x06 => Ok(Self::SwManuf),
            0x07 => Ok(Self::SecretLcTransition),
            0x08 => Ok(Self::Svn),
            0x09 => Ok(Self::VendorTest),
            0x0A => Ok(Self::VendorHashesManuf),
            0x0B => Ok(Self::VendorHashesProd),
            0x0C => Ok(Self::VendorRevocationsProd),
            0x0D => Ok(Self::VendorSecretProd),
            0x0E => Ok(Self::VendorNonSecretProd),
            _ => Err(McuError::ROM_OTP_FUSE_INVALID_PARTITION),
        }
    }
}

// ---------------------------------------------------------------------------
// Partition metadata
// ---------------------------------------------------------------------------

struct PartitionInfo {
    byte_offset: usize,
    byte_size: usize,
    is_secret: bool,
}

impl PartitionId {
    fn info(self) -> PartitionInfo {
        use PartitionId::*;
        match self {
            SwTestUnlock => PartitionInfo {
                byte_offset: fuses::SW_TEST_UNLOCK_PARTITION_BYTE_OFFSET,
                byte_size: fuses::SW_TEST_UNLOCK_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            SecretManuf => PartitionInfo {
                byte_offset: fuses::SECRET_MANUF_PARTITION_BYTE_OFFSET,
                byte_size: fuses::SECRET_MANUF_PARTITION_BYTE_SIZE,
                is_secret: true,
            },
            SecretProd0 => PartitionInfo {
                byte_offset: fuses::SECRET_PROD_PARTITION_0_BYTE_OFFSET,
                byte_size: fuses::SECRET_PROD_PARTITION_0_BYTE_SIZE,
                is_secret: true,
            },
            SecretProd1 => PartitionInfo {
                byte_offset: fuses::SECRET_PROD_PARTITION_1_BYTE_OFFSET,
                byte_size: fuses::SECRET_PROD_PARTITION_1_BYTE_SIZE,
                is_secret: true,
            },
            SecretProd2 => PartitionInfo {
                byte_offset: fuses::SECRET_PROD_PARTITION_2_BYTE_OFFSET,
                byte_size: fuses::SECRET_PROD_PARTITION_2_BYTE_SIZE,
                is_secret: true,
            },
            SecretProd3 => PartitionInfo {
                byte_offset: fuses::SECRET_PROD_PARTITION_3_BYTE_OFFSET,
                byte_size: fuses::SECRET_PROD_PARTITION_3_BYTE_SIZE,
                is_secret: true,
            },
            SwManuf => PartitionInfo {
                byte_offset: fuses::SW_MANUF_PARTITION_BYTE_OFFSET,
                byte_size: fuses::SW_MANUF_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            SecretLcTransition => PartitionInfo {
                byte_offset: fuses::SECRET_LC_TRANSITION_PARTITION_BYTE_OFFSET,
                byte_size: fuses::SECRET_LC_TRANSITION_PARTITION_BYTE_SIZE,
                is_secret: true,
            },
            Svn => PartitionInfo {
                byte_offset: fuses::SVN_PARTITION_BYTE_OFFSET,
                byte_size: fuses::SVN_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            VendorTest => PartitionInfo {
                byte_offset: fuses::VENDOR_TEST_PARTITION_BYTE_OFFSET,
                byte_size: fuses::VENDOR_TEST_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            VendorHashesManuf => PartitionInfo {
                byte_offset: fuses::VENDOR_HASHES_MANUF_PARTITION_BYTE_OFFSET,
                byte_size: fuses::VENDOR_HASHES_MANUF_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            VendorHashesProd => PartitionInfo {
                byte_offset: fuses::VENDOR_HASHES_PROD_PARTITION_BYTE_OFFSET,
                byte_size: fuses::VENDOR_HASHES_PROD_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            VendorRevocationsProd => PartitionInfo {
                byte_offset: fuses::VENDOR_REVOCATIONS_PROD_PARTITION_BYTE_OFFSET,
                byte_size: fuses::VENDOR_REVOCATIONS_PROD_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
            VendorSecretProd => PartitionInfo {
                byte_offset: fuses::VENDOR_SECRET_PROD_PARTITION_BYTE_OFFSET,
                byte_size: fuses::VENDOR_SECRET_PROD_PARTITION_BYTE_SIZE,
                is_secret: true,
            },
            VendorNonSecretProd => PartitionInfo {
                byte_offset: fuses::VENDOR_NON_SECRET_PROD_PARTITION_BYTE_OFFSET,
                byte_size: fuses::VENDOR_NON_SECRET_PROD_PARTITION_BYTE_SIZE,
                is_secret: false,
            },
        }
    }
}

// ===========================================================================
// MC_FUSE_READ  (0x4946_5052 / "IFPR")
// ===========================================================================
//
/// Validated DAI-read parameters returned by [`fuse_read_dai_params`].
pub struct FuseReadParams {
    pub base_word_addr: usize,
    pub words_to_read: usize,
    pub valid_bits: u32,
}

/// Validates a fuse-read request and returns the parameters needed to perform
/// the actual DAI word reads.  No data is read here -- the caller drives the
/// read loop so it can target any destination (stack buffer, SRAM registers, ...).
///
/// `entry` is a *byte offset* within the partition (must be word-aligned).
/// `max_words` caps the number of words that will be read.
pub fn fuse_read_dai_params(
    partition: u32,
    entry: u32,
    max_words: usize,
) -> Result<FuseReadParams, McuError> {
    let info = PartitionId::try_from(partition)?.info();

    if info.is_secret {
        crate::println!(
            "[otp-provision] Read denied: partition {} is secret",
            partition
        );
        return Err(McuError::ROM_OTP_FUSE_SECRET_READ_DENIED);
    }

    let entry_offset = entry as usize;
    if entry_offset >= info.byte_size || entry_offset % 4 != 0 {
        crate::println!(
            "[otp-provision] Entry out of bounds or unaligned: offset={}, size={}",
            entry_offset,
            info.byte_size
        );
        return Err(McuError::ROM_OTP_FUSE_ENTRY_OUT_OF_BOUNDS);
    }

    let remaining_bytes = info.byte_size - entry_offset;
    let remaining_words = (remaining_bytes + 3) / 4;
    let words_to_read = remaining_words.min(max_words);
    let base_word_addr = (info.byte_offset + entry_offset) / 4;

    crate::println!(
        "[otp-provision] DAI read: partition={}, entry={}, base_word_addr={}, words={}",
        HexWord(partition),
        entry,
        base_word_addr,
        words_to_read
    );

    let valid_bits = (remaining_bytes.min(words_to_read * 4) * 8) as u32;
    Ok(FuseReadParams {
        base_word_addr,
        words_to_read,
        valid_bits,
    })
}

/// Convenience wrapper: validates and reads fuse data into a caller-provided
/// buffer.  Kept for callers that already have a `&mut [u32]` destination.
pub fn fuse_read_dai(
    otp: &Otp,
    partition: u32,
    entry: u32,
    out_data: &mut [u32],
) -> Result<u32, McuError> {
    let params = fuse_read_dai_params(partition, entry, out_data.len())?;

    for (i, slot) in out_data.iter_mut().enumerate().take(params.words_to_read) {
        match otp.read_word(params.base_word_addr + i) {
            Ok(word) => *slot = word,
            Err(_) => {
                crate::println!(
                    "[otp-provision] DAI read error at word addr {}",
                    params.base_word_addr + i
                );
                return Err(McuError::ROM_OTP_FUSE_DAI_READ_ERROR);
            }
        }
    }

    Ok(params.valid_bits)
}

// ===========================================================================
// MC_FUSE_WRITE  (0x4946_5057 / "IFPW")
// ===========================================================================
//
/// Writes fuse bits via DAI.
///
/// `entry`     -- byte offset within the partition (must be word-aligned).
/// `start_bit` -- first bit to write (0 = LSB of the word at `entry`).
/// `length`    -- number of bits to write.
/// `data`      -- packed input words holding `length` bits, LSB-first.
///
/// Idempotent: writing identical data is a no-op.
/// Fails if any existing 1-bit would be cleared to 0.
/// Writes to buffered partitions do not take effect until the next reset.
pub fn fuse_write_dai(
    otp: &Otp,
    partition: u32,
    entry: u32,
    start_bit: u32,
    length: u32,
    data_len: usize,
    data_word: impl Fn(usize) -> u32,
) -> Result<(), McuError> {
    let info = PartitionId::try_from(partition)?.info();

    if length == 0 {
        return Err(McuError::ROM_OTP_FUSE_INVALID_LENGTH);
    }

    let entry_offset = entry as usize;
    if entry_offset >= info.byte_size || entry_offset % 4 != 0 {
        return Err(McuError::ROM_OTP_FUSE_ENTRY_OUT_OF_BOUNDS);
    }

    let data_area_bits = ((info.byte_size - entry_offset) * 8) as u32;
    let end_bit_excl = match start_bit.checked_add(length) {
        Some(v) => v,
        None => {
            crate::println!("[otp-provision] Write overflow: start_bit + length wraps u32");
            return Err(McuError::ROM_OTP_FUSE_ENTRY_OUT_OF_BOUNDS);
        }
    };
    if end_bit_excl > data_area_bits {
        crate::println!(
            "[otp-provision] Write out of bounds: start_bit({}) + length({}) > {}",
            start_bit,
            length,
            data_area_bits
        );
        return Err(McuError::ROM_OTP_FUSE_ENTRY_OUT_OF_BOUNDS);
    }

    let required_data_words = ((length + 31) / 32) as usize;
    if data_len < required_data_words {
        return Err(McuError::ROM_OTP_FUSE_INVALID_LENGTH);
    }

    let base_word_addr = (info.byte_offset + entry_offset) / 4;
    let first_word_idx = (start_bit / 32) as usize;
    let end_bit = end_bit_excl - 1; // safe: length > 0 validated above
    let last_word_idx = (end_bit / 32) as usize;

    crate::println!(
        "[otp-provision] DAI write: partition={}, entry={}, start_bit={}, length={}, words {}..{}",
        HexWord(partition),
        entry,
        start_bit,
        length,
        first_word_idx,
        last_word_idx
    );

    let mut data_bit_consumed: u32 = 0;

    for word_idx in first_word_idx..=last_word_idx {
        let word_addr = base_word_addr + word_idx;

        let word_bit_start = if word_idx == first_word_idx {
            start_bit % 32
        } else {
            0
        };
        let word_bit_end = if word_idx == last_word_idx {
            end_bit % 32
        } else {
            31
        };
        let bits_in_word = word_bit_end - word_bit_start + 1;

        let mask = if bits_in_word >= 32 {
            0xFFFF_FFFFu32
        } else {
            ((1u32 << bits_in_word) - 1) << word_bit_start
        };

        let src_word_idx = (data_bit_consumed / 32) as usize;
        let src_bit_off = data_bit_consumed % 32;

        let mut new_bits: u32 = if src_word_idx < data_len {
            data_word(src_word_idx) >> src_bit_off
        } else {
            0
        };
        if src_bit_off > 0 && (src_word_idx + 1) < data_len {
            new_bits |= data_word(src_word_idx + 1) << (32 - src_bit_off);
        }

        let bits_mask = if bits_in_word >= 32 {
            0xFFFF_FFFFu32
        } else {
            (1u32 << bits_in_word) - 1
        };
        new_bits = (new_bits & bits_mask) << word_bit_start;

        let current = match otp.read_word(word_addr) {
            Ok(v) => v,
            Err(_) => {
                crate::println!("[otp-provision] DAI read error at word addr {}", word_addr);
                return Err(McuError::ROM_OTP_FUSE_DAI_READ_ERROR);
            }
        };

        if (current & mask) & !new_bits != 0 {
            crate::println!(
                "[otp-provision] Bit-clear conflict at word {}: current={}, requested={}",
                word_addr,
                HexWord(current & mask),
                HexWord(new_bits)
            );
            return Err(McuError::ROM_OTP_FUSE_BIT_CLEAR_NOT_ALLOWED);
        }

        let write_value = current | new_bits;
        if write_value != current {
            match otp.write_word(word_addr, write_value) {
                Ok(_) => {}
                Err(_) => {
                    crate::println!("[otp-provision] DAI write error at word addr {}", word_addr);
                    return Err(McuError::ROM_OTP_FUSE_DAI_WRITE_ERROR);
                }
            }
        }

        data_bit_consumed += bits_in_word;
    }

    Ok(())
}

// ===========================================================================
// MC_FUSE_LOCK_PARTITION  (0x4946_504B / "IFPK")
// ===========================================================================
//
/// Locks a partition by computing and writing its integrity digest via DAI.
/// Idempotent: locking an already-locked partition is a no-op.
/// Locking does not fully take effect until the next reset.
pub fn fuse_lock_partition_dai(otp: &Otp, partition: u32) -> Result<(), McuError> {
    let info = PartitionId::try_from(partition)?.info();

    crate::println!(
        "[otp-provision] DAI lock: partition={}, base_addr={}",
        HexWord(partition),
        HexWord(info.byte_offset as u32)
    );

    match otp.finalize_digest(info.byte_offset) {
        Ok(()) => {
            crate::println!(
                "[otp-provision] Partition {} locked successfully",
                partition
            );
            Ok(())
        }
        Err(_) => {
            crate::println!("[otp-provision] Failed to lock partition {}", partition);
            Err(McuError::ROM_OTP_FUSE_LOCK_ERROR)
        }
    }
}
