// Licensed under the Apache-2.0 license

use crate::{target_dir, ImageCfg};
use anyhow::{bail, Result};
use serde::Serialize;
use std::collections::HashSet;

#[derive(Serialize)]
struct AttestationManifestConfigToml {
    vendor: String,
    model: String,
    components: Vec<AttestationManifestComponentToml>,
}

#[derive(Serialize)]
struct AttestationManifestComponentToml {
    fw_id: u32,
    is_tcb: bool,
    is_ak_target: bool,
}

pub(crate) fn write_config(
    vendor: &str,
    model: &str,
    soc_images: &[ImageCfg],
    generated_by: &str,
    log_prefix: &str,
) -> Result<()> {
    let config_file = config_source(vendor, model, soc_images, generated_by)?;
    let generated_dir = target_dir().join("generated");
    std::fs::create_dir_all(&generated_dir)?;
    let path = generated_dir.join("attestation_manifest.toml");
    std::fs::write(&path, config_file)?;
    println!(
        "{} Attestation Manifest config at: {}",
        log_prefix,
        path.display()
    );
    Ok(())
}

fn config_source(
    vendor: &str,
    model: &str,
    soc_images: &[ImageCfg],
    generated_by: &str,
) -> Result<String> {
    let mut seen_fw_ids = HashSet::new();
    let mut components = Vec::new();
    for image in soc_images {
        if !seen_fw_ids.insert(image.image_id) {
            bail!(
                "duplicate SoC image fw_id {} in Attestation Manifest config source",
                image.image_id
            );
        }
        components.push(AttestationManifestComponentToml {
            fw_id: image.image_id,
            is_tcb: image.is_tcb,
            is_ak_target: image.is_ak_target,
        });
    }

    let config = AttestationManifestConfigToml {
        vendor: vendor.to_string(),
        model: model.to_string(),
        components,
    };

    let mut source = String::new();
    source.push_str("# Licensed under the Apache-2.0 license\n");
    source.push_str("# AUTO-GENERATED FILE. DO NOT EDIT.\n");
    source.push_str(&format!("# Generated by {generated_by}\n"));
    source.push_str(&toml::to_string(&config)?);
    Ok(source)
}
