// Licensed under the Apache-2.0 license

use crate::ImageCfg;
use anyhow::{bail, Result};
use serde::Serialize;
use std::{collections::HashSet, path::Path};

#[derive(Serialize)]
struct AttestationManifestConfigToml {
    vendor: String,
    model: String,
    components: Vec<AttestationManifestComponentToml>,
}

#[derive(Serialize)]
struct AttestationManifestComponentToml {
    fw_id: u32,
    is_tcb: bool,
    is_ak_target: bool,
}

#[derive(Serialize)]
struct SocImageDescriptorsConfigToml {
    images: Vec<SocImageDescriptorToml>,
}

#[derive(Serialize)]
struct SocImageDescriptorToml {
    fw_id: u32,
}

pub(crate) fn write_config(
    vendor: &str,
    model: &str,
    soc_images: &[ImageCfg],
    generated_by: &str,
    log_prefix: &str,
) -> Result<()> {
    write_config_to_target_dir(
        &crate::target_dir(),
        vendor,
        model,
        soc_images,
        generated_by,
        log_prefix,
    )
}

pub(crate) fn write_config_to_target_dir(
    target_dir: &Path,
    vendor: &str,
    model: &str,
    soc_images: &[ImageCfg],
    generated_by: &str,
    log_prefix: &str,
) -> Result<()> {
    let config_file = config_source(vendor, model, soc_images, generated_by)?;
    let generated_dir = target_dir.join("generated");
    std::fs::create_dir_all(&generated_dir)?;
    let path = generated_dir.join("attestation_manifest.toml");
    std::fs::write(&path, config_file)?;
    println!(
        "{} Attestation Manifest config at: {}",
        log_prefix,
        path.display()
    );
    let descriptor_config_file = soc_image_descriptors_config_source(soc_images)?;
    let descriptor_path = generated_dir.join("soc_image_descriptors.toml");
    std::fs::write(&descriptor_path, descriptor_config_file)?;
    println!(
        "{} SoC image descriptor config at: {}",
        log_prefix,
        descriptor_path.display()
    );
    Ok(())
}

fn config_source(
    vendor: &str,
    model: &str,
    soc_images: &[ImageCfg],
    generated_by: &str,
) -> Result<String> {
    let mut seen_fw_ids = HashSet::new();
    let mut components = Vec::new();
    for image in soc_images {
        if !seen_fw_ids.insert(image.image_id) {
            bail!(
                "duplicate SoC image fw_id {} in Attestation Manifest config source",
                image.image_id
            );
        }
        components.push(AttestationManifestComponentToml {
            fw_id: image.image_id,
            is_tcb: image.is_tcb,
            is_ak_target: image.is_ak_target,
        });
    }

    let config = AttestationManifestConfigToml {
        vendor: vendor.to_string(),
        model: model.to_string(),
        components,
    };

    let mut source = String::new();
    source.push_str("# Licensed under the Apache-2.0 license\n");
    source.push_str("# AUTO-GENERATED FILE. DO NOT EDIT.\n");
    source.push_str(&format!("# Generated by {generated_by}\n"));
    source.push_str(&toml::to_string(&config)?);
    Ok(source)
}

fn soc_image_descriptors_config_source(soc_images: &[ImageCfg]) -> Result<String> {
    let mut images = Vec::new();
    for image in soc_images {
        images.push(SocImageDescriptorToml {
            fw_id: image.image_id,
        });
    }
    let config = SocImageDescriptorsConfigToml { images };

    let mut source = String::new();
    source.push_str("# Licensed under the Apache-2.0 license\n");
    source.push_str("# AUTO-GENERATED FILE. DO NOT EDIT.\n");
    source.push_str("# Generated from the same ImageCfg source as the SoC Manifest metadata\n");
    source.push_str(&toml::to_string(&config)?);
    Ok(source)
}
