# Licensed under the Apache-2.0 license

[profile.nightly]
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "5m", terminate-after = 6 }

[profile.nightly.junit]
path = "/tmp/junit.xml"
store-success-output = true
store-failure-output = true

[profile.nightly-emulator]
failure-output = "immediate-final"
fail-fast = false
slow-timeout = { period = "30s", terminate-after = 30 }
# Disable tests that are currently failing in CI
default-filter = """
!(package(caliptra-mcu-tests-integration) and test(test_active_i3c::test::test_boot_with_i3c1_active)
| package(caliptra-mcu-tests-integration) and test(test_bare_metal::test::test_bare_metal_runtime_boot)
| package(caliptra-mcu-tests-integration) and test(test_dot::test::test_dot_override_challenge_success)
| package(caliptra-mcu-tests-integration) and test(test_dot::test::test_dot_override_invalid_signatures_fails)
| package(caliptra-mcu-tests-integration) and test(test_dot::test::test_dot_recovery_backup_blob_invalid_hmac)
| package(caliptra-mcu-tests-integration) and test(test_dot::test::test_dot_unlocked_state_custom_owner_keys)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_invalid_caliptra_image)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_invalid_manifest)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_invalid_mcu_image)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_invalid_soc_image)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_missing_caliptra_image)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_successful)
| package(caliptra-mcu-tests-integration) and test(test_firmware_update::test::test_firmware_update_flash_successful_fast)
| package(caliptra-mcu-tests-integration) and test(test_soc_boot::test::test_streaming_soc_boot_invalid_load_address)
| package(caliptra-mcu-tests-integration) and test(test_soc_boot::test::test_streaming_soc_boot_one_component_id_for_all)
| package(caliptra-mcu-tests-integration) and test(test_soc_boot::test::test_streaming_soc_boot_successful)
| package(caliptra-mcu-tests-integration) and test(test_soc_boot::test::test_streaming_soc_boot_successful_non_identical)
| package(caliptra-mcu-tests-integration) and test(test_soc_boot::test::test_streaming_soc_boot_unauthorized_image)
| package(caliptra-mcu-tests-integration) and test(test::test_mctp_user_loopback)
| package(caliptra-mcu-tests-integration) and test(test::test_mcu_mbox_driver)
| package(caliptra-mcu-tests-integration) and test(test::test_mcu_mbox_soc_requester_loopback)
| package(caliptra-mcu-tests-integration) and test(test::test_mcu_svn_gt_fuse)
| package(caliptra-mcu-tests-integration) and test(test::test_mcu_svn_lt_fuse)
| package(caliptra-mcu-hw-model) and test(model_emulated::test::test_new_unbooted))
"""

[profile.nightly-emulator.junit]
path = "/tmp/junit.xml"
store-success-output = true
store-failure-output = true

[profile.nightly-ci]
inherits = "nightly"
default-filter = """
(package(caliptra-mcu-hw-model)
    - test(model_emulated::test::test_new_unbooted)) |
(package(caliptra-mcu-tests-integration) and test(test_jtag_taps)) |
(package(caliptra-mcu-tests-integration) and test(test_lc_transitions)) |
(package(caliptra-mcu-tests-integration) and test(test_manuf_debug_unlock)) |
(package(caliptra-mcu-tests-integration) and test(test_prod_debug_unlock)) |
(package(caliptra-mcu-tests-integration) and test(test_uds)) |
(package(caliptra-mcu-tests-integration) and test(test_imaginary_flash_controller)) |
(package(caliptra-mcu-tests-integration) and test(test_fw_update_e2e)) |
(package(caliptra-mcu-tests-integration) and test(test_mctp_capsule_loopback)) |
(package(caliptra-mcu-tests-integration) and test(test_mctp_vdm_cmds)) |
(package(caliptra-mcu-tests-integration) and test(test_mcu_mbox_usermode)) |
(package(caliptra-mcu-tests-integration) and test(test_mcu_mbox_cmds)) |
(package(caliptra-mcu-tests-integration) and test(test_mcu_mbox_fips_self_test)) |
(package(caliptra-mcu-tests-integration) and test(test_mcu_mbox_fips_periodic)) |
(package(caliptra-mcu-tests-integration) and test(test_i3c_constant_writes)) |
(package(caliptra-mcu-tests-integration) and test(test_i3c_simple)) |
(package(caliptra-mcu-tests-integration) and test(test_i3c_services_ping)) |
(package(caliptra-mcu-tests-integration) and test(test_i3c_services_unknown_cmd)) |
(package(caliptra-mcu-tests-integration) and test(test_sw_digest_lock)) |
(package(caliptra-mcu-tests-integration) and test(test_otp_blank_check)) |
(package(caliptra-mcu-tests-integration) and test(test_otp_scramble_check)) |
(package(caliptra-mcu-tests-integration) and test(test_bootfsm_timeout)) |
(package(caliptra-mcu-tests-integration) and test(test_lc_ctrl)) |
(package(caliptra-mcu-tests-integration) and test(test_raw_lifecycle_boot))
"""
# disabled for now due to flakiness of firmware update
# (package(caliptra-mcu-tests-integration) and test(test_firmware_update_streaming_fpga)) |
