// Licensed under the Apache-2.0 license

use crate::registers::{file_check_contents, rustfmt, write_file};
use anyhow::Result;
use fusegen::{OtpMmap, HEADER_PREFIX, HEADER_SUFFIX, OTP_CTRL_MMAP_DEFAULT_PATH};
use mcu_builder::PROJECT_ROOT;
use registers_generator::snake_case;
use std::fmt::Write;
use std::path::{Path, PathBuf};

// Default in-field provisioning fuse configuration.
const IFP_SPECIFIC_FUSES_DEFAULT_PATH: &str = "hw/fuses.hjson";

fn get_file_path_or_default(input_path: Option<&Path>, default: &str) -> PathBuf {
    if let Some(path) = input_path {
        path.to_path_buf()
    } else {
        PROJECT_ROOT.join(default)
    }
}

/// Autogenerate fuse code.
pub(crate) fn autogen_fuses(
    check: bool,
    dest_dir: &Path,
    fuses_hjson_path: Option<&Path>,
    otp_mmap_hjson_path: Option<&Path>,
) -> Result<()> {
    let file_action = if check {
        file_check_contents
    } else {
        write_file
    };

    // Generate combined output from both functions
    let mut header = HEADER_PREFIX.to_string();

    // Parse OTP mmap for partition info
    let mmap_hjson = get_file_path_or_default(otp_mmap_hjson_path, OTP_CTRL_MMAP_DEFAULT_PATH);
    let otp: OtpMmap = serde_hjson::from_str(std::fs::read_to_string(&mmap_hjson)?.as_str())?;
    let partition_mmap = build_partition_mmap(&otp);

    // Generate partition fuses output
    let partition_output = generate_fuse_partitions_from_otp(&otp)?;

    // Generate detailed fuses output if the file exists
    let fuses_hjson = get_file_path_or_default(fuses_hjson_path, IFP_SPECIFIC_FUSES_DEFAULT_PATH);
    let detailed_output = if fuses_hjson.exists() {
        Some(generate_detailed_fuses(fuses_hjson_path, &partition_mmap)?)
    } else {
        None
    };

    // Build combined header
    write!(
        &mut header,
        "\n generated by registers_generator with {}",
        mmap_hjson.file_name().unwrap().to_string_lossy(),
    )?;

    if detailed_output.is_some() {
        write!(
            &mut header,
            " and {}",
            fuses_hjson.file_name().unwrap().to_string_lossy()
        )?;
    }

    header.push_str(HEADER_SUFFIX);

    // Combine outputs
    let mut combined_output = partition_output;
    if let Some(detailed) = detailed_output {
        combined_output += "\n";
        combined_output += &detailed;
    }

    // Write combined output to fuses.rs
    let fuses_file = dest_dir.join("fuses.rs");
    file_action(&fuses_file, &rustfmt(&(header + &combined_output))?)?;

    Ok(())
}

/// Build a map of partition name → PartitionMmapInfo from the parsed OTP mmap.
fn build_partition_mmap(
    otp: &OtpMmap,
) -> std::collections::HashMap<String, mcu_fuses_generator::codegen::PartitionMmapInfo> {
    use mcu_fuses_generator::codegen::{PartitionItemInfo, PartitionMmapInfo};

    let mut map = std::collections::HashMap::new();
    let mut offset: usize = 0;
    for (partition_index, partition) in otp.partitions.iter().enumerate() {
        let digest_size: usize = if partition.hw_digest || partition.sw_digest {
            8
        } else {
            0
        };
        let calculated_size: usize = partition
            .items
            .iter()
            .map(|i| i.size.parse::<usize>().unwrap())
            .sum();

        let calculated_size = if digest_size == 8 {
            calculated_size.next_multiple_of(8) + digest_size
        } else {
            calculated_size.next_multiple_of(4)
        };

        let size = partition
            .size
            .as_ref()
            .map(|s| s.parse::<usize>().unwrap())
            .unwrap_or(calculated_size);

        let mut items = Vec::new();
        let mut item_offset = offset;
        for (entry_num, item) in partition.items.iter().enumerate() {
            let item_size = item.size.parse::<usize>().unwrap();
            let item_name_lower = snake_case(&item.name);
            if item_name_lower.to_ascii_lowercase().ends_with("digest") {
                item_offset = item_offset.next_multiple_of(8);
            }
            items.push(PartitionItemInfo {
                name: item.name.clone(),
                byte_offset: item_offset,
                byte_size: item_size,
                entry_num,
            });
            item_offset += item_size;
        }

        map.insert(
            partition.name.clone(),
            PartitionMmapInfo {
                partition_index,
                byte_offset: offset,
                byte_size: size,
                items,
            },
        );

        offset += size;
    }

    map
}

/// Autogenerate fuse map code from pre-parsed OTP mmap.
fn generate_fuse_partitions_from_otp(otp: &OtpMmap) -> Result<String> {
    let mut output = "".to_string();

    // OtpPartitionInfo struct
    output += "/// Describes an OTP partition with its location, size, and digest properties.\n";
    output += "#[derive(Debug, Clone, Copy)]\n";
    output += "pub struct OtpPartitionInfo {\n";
    output += "    /// Partition name.\n";
    output += "    pub name: &'static str,\n";
    output += "    /// Byte offset of the partition within the OTP address space.\n";
    output += "    pub byte_offset: usize,\n";
    output += "    /// Total byte size of the partition (including the digest field if present).\n";
    output += "    pub byte_size: usize,\n";
    output += "    /// Whether this partition supports a software-computed digest.\n";
    output += "    pub sw_digest: bool,\n";
    output += "    /// Whether this partition has a hardware-computed digest.\n";
    output += "    pub hw_digest: bool,\n";
    output += "    /// Byte offset of the 8-byte digest field within OTP (if sw_digest or hw_digest is true).\n";
    output += "    pub digest_offset: Option<usize>,\n";
    output += "}\n";

    let mut const_output = "".to_string();
    let mut partition_entries = Vec::new();
    let mut offset = 0;

    otp.partitions.iter().for_each(|partition| {
        let name = snake_case(&partition.name);
        let has_digest = partition.hw_digest || partition.sw_digest;
        let digest_size: usize = if has_digest { 8 } else { 0 };
        let calculated_size = partition
            .items
            .iter()
            .map(|i| i.size.parse::<usize>().unwrap())
            .sum::<usize>();

        let calculated_size = if digest_size == 8 {
            // digests need to be aligned to 8-byte boundary
            calculated_size.next_multiple_of(8) + digest_size
        } else {
            // partitions need to be aligned to 4-byte boundary
            calculated_size.next_multiple_of(4)
        };

        let size = partition
            .size
            .as_ref()
            .map(|s| s.parse::<usize>().unwrap())
            .unwrap_or(calculated_size);

        if name != "vendor_test_partition" {
            assert_eq!(calculated_size, size);
        }

        // Digest is always the last 8 bytes of the partition
        let digest_offset = if has_digest {
            format!("Some(0x{:x})", offset + size - 8)
        } else {
            "None".to_string()
        };

        partition_entries.push(format!(
            "OtpPartitionInfo {{ name: \"{}\", byte_offset: 0x{:x}, byte_size: 0x{:x}, sw_digest: {}, hw_digest: {}, digest_offset: {} }}",
            name, offset, size, partition.sw_digest, partition.hw_digest, digest_offset
        ));

        const_output += &format!(
            "pub const {}_BYTE_OFFSET: usize = 0x{:x};\n",
            name.to_uppercase(),
            offset
        );
        const_output += &format!(
            "pub const {}_BYTE_SIZE: usize = 0x{:x};\n",
            name.to_uppercase(),
            size,
        );
        offset += size;
    });

    // Generate the OTP_PARTITIONS array
    output += "/// All OTP partitions with their locations and digest properties.\npub const OTP_PARTITIONS: &[OtpPartitionInfo] = &[\n";
    for e in &partition_entries {
        writeln!(&mut output, "    {},", e)?;
    }
    output += "];\n";

    // Generate named constants for each partition
    for (i, partition) in otp.partitions.iter().enumerate() {
        let name = snake_case(&partition.name);
        output += &format!(
            "pub const {}: &OtpPartitionInfo = &OTP_PARTITIONS[{}];\n",
            name.to_uppercase(),
            i
        );
    }

    output += &const_output;

    Ok(output)
}

/// Generate more detailed fuse definitions from the MCU-specific file.
fn generate_detailed_fuses(
    fuses_hjson_path: Option<&Path>,
    partition_mmap: &std::collections::HashMap<
        String,
        mcu_fuses_generator::codegen::PartitionMmapInfo,
    >,
) -> Result<String> {
    let fuses_hjson = get_file_path_or_default(fuses_hjson_path, IFP_SPECIFIC_FUSES_DEFAULT_PATH);
    let hjson_content = std::fs::read_to_string(&fuses_hjson)?;
    let config = mcu_fuses_generator::schema::parse_fuse_hjson_str(&hjson_content)?;
    let generated_code =
        mcu_fuses_generator::codegen::generate_fuses(&config, Some(partition_mmap))?;
    Ok(generated_code)
}
