// Licensed under the Apache-2.0 license.
//
// generated by caliptra_mcu_registers_generator with caliptra-ss repo at b5718a0f7fe7936b5082a8dfc23add896755af3a
//
pub mod axicdma;
pub mod doe_mbox;
pub mod el2_pic;
pub mod i3c;
pub mod i3c1;
pub mod lc;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod primary_flash;
pub mod root_bus;
pub mod secondary_flash;
pub mod sha512_acc;
pub mod soc;
pub mod stub_warnings;
