// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at b3fdf7e8c6d73fd49d44d2772636922bd0148f06
//
pub mod axicdma;
pub mod doe_mbox;
pub mod el2_pic;
pub mod i3c;
pub mod lc;
pub mod mbox;
pub mod mci;
pub mod otp;
pub mod primary_flash;
pub mod root_bus;
pub mod secondary_flash;
pub mod sha512_acc;
pub mod soc;
