// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 9022fc2a57bb9af2f3ebc2376b98a807812e2e0f
//

use std::sync::atomic::{AtomicBool, Ordering};

static WARN_ON_STUB: AtomicBool = AtomicBool::new(true);

/// Enable or disable warning logs when auto-generated register stubs
/// handle a read/write that was not overridden by the peripheral implementation.
pub fn set_stub_warnings(enabled: bool) {
    WARN_ON_STUB.store(enabled, Ordering::Relaxed);
}

/// Returns `true` if stub warning logs are enabled.
#[inline]
pub fn stub_warnings_enabled() -> bool {
    WARN_ON_STUB.load(Ordering::Relaxed)
}
