// Licensed under the Apache-2.0 license.
//
// generated by registers_generator with caliptra-ss repo at 3350c70a296bf897abe8c02e5ec0da69cc83ee16
//
#[allow(unused_imports)]
use tock_registers::interfaces::{Readable, Writeable};
pub trait UsbdevPeripheral {
    fn set_dma_ram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn set_dma_rom_sram(&mut self, _ram: std::rc::Rc<std::cell::RefCell<caliptra_emu_bus::Ram>>) {}
    fn register_event_channels(
        &mut self,
        _events_to_caliptra: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_caliptra: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
        _events_to_mcu: std::sync::mpsc::Sender<caliptra_emu_bus::Event>,
        _events_from_mcu: std::sync::mpsc::Receiver<caliptra_emu_bus::Event>,
    ) {
    }
    fn poll(&mut self) {}
    fn warm_reset(&mut self) {}
    fn update_reset(&mut self) {}
    fn generated(&mut self) -> Option<&mut UsbdevGenerated> {
        None
    }
    fn read_intr_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::IntrState::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_intr_state();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_intr_state(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::IntrState::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_intr_state(val);
        }
    }
    fn read_intr_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::IntrEnable::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_intr_enable();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_intr_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::IntrEnable::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_intr_enable(val);
        }
    }
    fn write_intr_test(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::IntrTest::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_intr_test(val);
        }
    }
    fn write_alert_test(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::AlertTest::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_alert_test(val);
        }
    }
    fn read_usbctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::Usbctrl::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_usbctrl();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_usbctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Usbctrl::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_usbctrl(val);
        }
    }
    fn read_ep_out_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::EpOutEnable::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_ep_out_enable();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_ep_out_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::EpOutEnable::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_ep_out_enable(val);
        }
    }
    fn read_ep_in_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::EpInEnable::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_ep_in_enable();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_ep_in_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::EpInEnable::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_ep_in_enable(val);
        }
    }
    fn read_usbstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::Usbstat::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_usbstat();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_avoutbuffer(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Avoutbuffer::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_avoutbuffer(val);
        }
    }
    fn write_avsetupbuffer(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Avsetupbuffer::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_avsetupbuffer(val);
        }
    }
    fn read_rxfifo(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::Rxfifo::Register>
    {
        if let Some(generated) = self.generated() {
            return generated.read_rxfifo();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_rxenable_setup(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::RxenableSetup::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_rxenable_setup();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_rxenable_setup(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::RxenableSetup::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_rxenable_setup(val);
        }
    }
    fn read_rxenable_out(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::RxenableOut::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_rxenable_out();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_rxenable_out(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::RxenableOut::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_rxenable_out(val);
        }
    }
    fn read_set_nak_out(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::SetNakOut::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_set_nak_out();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_set_nak_out(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::SetNakOut::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_set_nak_out(val);
        }
    }
    fn read_in_sent(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::InSent::Register>
    {
        if let Some(generated) = self.generated() {
            return generated.read_in_sent();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_in_sent(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InSent::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_in_sent(val);
        }
    }
    fn read_out_stall(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::OutStall::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_out_stall();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_out_stall(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::OutStall::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_out_stall(val);
        }
    }
    fn read_in_stall(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::InStall::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_in_stall();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_in_stall(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InStall::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_in_stall(val);
        }
    }
    fn read_configin_0(
        &mut self,
        index: usize,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::Configin0::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_configin_0(index);
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_configin_0(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Configin0::Register,
        >,
        index: usize,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_configin_0(val, index);
        }
    }
    fn read_out_iso(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::OutIso::Register>
    {
        if let Some(generated) = self.generated() {
            return generated.read_out_iso();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_out_iso(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::OutIso::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_out_iso(val);
        }
    }
    fn read_in_iso(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::InIso::Register>
    {
        if let Some(generated) = self.generated() {
            return generated.read_in_iso();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_in_iso(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InIso::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_in_iso(val);
        }
    }
    fn read_out_data_toggle(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::OutDataToggle::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_out_data_toggle();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_out_data_toggle(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::OutDataToggle::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_out_data_toggle(val);
        }
    }
    fn read_in_data_toggle(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::InDataToggle::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_in_data_toggle();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_in_data_toggle(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InDataToggle::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_in_data_toggle(val);
        }
    }
    fn read_phy_pins_sense(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::PhyPinsSense::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_phy_pins_sense();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn read_phy_pins_drive(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::PhyPinsDrive::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_phy_pins_drive();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_phy_pins_drive(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::PhyPinsDrive::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_phy_pins_drive(val);
        }
    }
    fn read_phy_config(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::PhyConfig::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_phy_config();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_phy_config(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::PhyConfig::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_phy_config(val);
        }
    }
    fn write_wake_control(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::WakeControl::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_wake_control(val);
        }
    }
    fn read_wake_events(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::WakeEvents::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_wake_events();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_fifo_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::FifoCtrl::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_fifo_ctrl(val);
        }
    }
    fn read_count_out(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountOut::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_count_out();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_count_out(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountOut::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_count_out(val);
        }
    }
    fn read_count_in(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountIn::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_count_in();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_count_in(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountIn::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_count_in(val);
        }
    }
    fn read_count_nodata_in(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountNodataIn::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_count_nodata_in();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_count_nodata_in(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountNodataIn::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_count_nodata_in(val);
        }
    }
    fn read_count_errors(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountErrors::Register,
    > {
        if let Some(generated) = self.generated() {
            return generated.read_count_errors();
        }
        caliptra_emu_bus::ReadWriteRegister::new(0)
    }
    fn write_count_errors(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountErrors::Register,
        >,
    ) {
        if let Some(generated) = self.generated() {
            generated.write_count_errors(val);
        }
    }
    fn read_buffer(&mut self, index: usize) -> caliptra_emu_types::RvData {
        if let Some(generated) = self.generated() {
            return generated.read_buffer(index);
        }
        0
    }
    fn write_buffer(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        if let Some(generated) = self.generated() {
            generated.write_buffer(val, index);
        }
    }
}
#[derive(Clone, Debug)]
pub struct UsbdevGenerated {
    intr_state: caliptra_emu_types::RvData,
    intr_enable: caliptra_emu_types::RvData,
    intr_test: caliptra_emu_types::RvData,
    alert_test: caliptra_emu_types::RvData,
    usbctrl: caliptra_emu_types::RvData,
    ep_out_enable: caliptra_emu_types::RvData,
    ep_in_enable: caliptra_emu_types::RvData,
    usbstat: caliptra_emu_types::RvData,
    avoutbuffer: caliptra_emu_types::RvData,
    avsetupbuffer: caliptra_emu_types::RvData,
    rxfifo: caliptra_emu_types::RvData,
    rxenable_setup: caliptra_emu_types::RvData,
    rxenable_out: caliptra_emu_types::RvData,
    set_nak_out: caliptra_emu_types::RvData,
    in_sent: caliptra_emu_types::RvData,
    out_stall: caliptra_emu_types::RvData,
    in_stall: caliptra_emu_types::RvData,
    configin_0: Vec<caliptra_emu_types::RvData>,
    out_iso: caliptra_emu_types::RvData,
    in_iso: caliptra_emu_types::RvData,
    out_data_toggle: caliptra_emu_types::RvData,
    in_data_toggle: caliptra_emu_types::RvData,
    phy_pins_sense: caliptra_emu_types::RvData,
    phy_pins_drive: caliptra_emu_types::RvData,
    phy_config: caliptra_emu_types::RvData,
    wake_control: caliptra_emu_types::RvData,
    wake_events: caliptra_emu_types::RvData,
    fifo_ctrl: caliptra_emu_types::RvData,
    count_out: caliptra_emu_types::RvData,
    count_in: caliptra_emu_types::RvData,
    count_nodata_in: caliptra_emu_types::RvData,
    count_errors: caliptra_emu_types::RvData,
    buffer: Vec<caliptra_emu_types::RvData>,
}
impl Default for UsbdevGenerated {
    fn default() -> Self {
        Self {
            intr_state: 0 as caliptra_emu_types::RvData,
            intr_enable: 0 as caliptra_emu_types::RvData,
            intr_test: 0 as caliptra_emu_types::RvData,
            alert_test: 0 as caliptra_emu_types::RvData,
            usbctrl: 0 as caliptra_emu_types::RvData,
            ep_out_enable: 0 as caliptra_emu_types::RvData,
            ep_in_enable: 0 as caliptra_emu_types::RvData,
            usbstat: 0x8000_0000 as caliptra_emu_types::RvData,
            avoutbuffer: 0 as caliptra_emu_types::RvData,
            avsetupbuffer: 0 as caliptra_emu_types::RvData,
            rxfifo: 0 as caliptra_emu_types::RvData,
            rxenable_setup: 0 as caliptra_emu_types::RvData,
            rxenable_out: 0 as caliptra_emu_types::RvData,
            set_nak_out: 0 as caliptra_emu_types::RvData,
            in_sent: 0 as caliptra_emu_types::RvData,
            out_stall: 0 as caliptra_emu_types::RvData,
            in_stall: 0 as caliptra_emu_types::RvData,
            configin_0: vec![0 as caliptra_emu_types::RvData; 12],
            out_iso: 0 as caliptra_emu_types::RvData,
            in_iso: 0 as caliptra_emu_types::RvData,
            out_data_toggle: 0 as caliptra_emu_types::RvData,
            in_data_toggle: 0 as caliptra_emu_types::RvData,
            phy_pins_sense: 0 as caliptra_emu_types::RvData,
            phy_pins_drive: 0 as caliptra_emu_types::RvData,
            phy_config: 4 as caliptra_emu_types::RvData,
            wake_control: 0 as caliptra_emu_types::RvData,
            wake_events: 0 as caliptra_emu_types::RvData,
            fifo_ctrl: 0 as caliptra_emu_types::RvData,
            count_out: 0 as caliptra_emu_types::RvData,
            count_in: 0 as caliptra_emu_types::RvData,
            count_nodata_in: 0 as caliptra_emu_types::RvData,
            count_errors: 0 as caliptra_emu_types::RvData,
            buffer: vec![0 as caliptra_emu_types::RvData; 512],
        }
    }
}
impl UsbdevGenerated {
    pub fn new() -> Self {
        Self::default()
    }
    fn reset_state(&mut self) {
        *self = Self::default();
    }
}
impl UsbdevPeripheral for UsbdevGenerated {
    fn generated(&mut self) -> Option<&mut UsbdevGenerated> {
        Some(self)
    }
    fn warm_reset(&mut self) {
        self.reset_state();
    }
    fn update_reset(&mut self) {
        self.reset_state();
    }
    fn read_intr_state(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::IntrState::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.intr_state)
    }
    fn write_intr_state(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::IntrState::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intr_state;
        let mut new_val = current_val;
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1000 as caliptra_emu_types::RvData))
            | (write_val & (0x1000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1_0000 as caliptra_emu_types::RvData));
        self.intr_state = new_val;
    }
    fn read_intr_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::IntrEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.intr_enable)
    }
    fn write_intr_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::IntrEnable::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intr_enable;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1000 as caliptra_emu_types::RvData))
            | (write_val & (0x1000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x2_0000 as caliptra_emu_types::RvData));
        self.intr_enable = new_val;
    }
    fn write_intr_test(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::IntrTest::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.intr_test;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1000 as caliptra_emu_types::RvData))
            | (write_val & (0x1000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x2_0000 as caliptra_emu_types::RvData));
        self.intr_test = new_val;
    }
    fn write_alert_test(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::AlertTest::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.alert_test;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        self.alert_test = new_val;
    }
    fn read_usbctrl(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::Usbctrl::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.usbctrl)
    }
    fn write_usbctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Usbctrl::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.usbctrl;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x7f_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x7f_0000 as caliptra_emu_types::RvData));
        self.usbctrl = new_val;
    }
    fn read_ep_out_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::EpOutEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.ep_out_enable)
    }
    fn write_ep_out_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::EpOutEnable::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.ep_out_enable;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.ep_out_enable = new_val;
    }
    fn read_ep_in_enable(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::EpInEnable::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.ep_in_enable)
    }
    fn write_ep_in_enable(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::EpInEnable::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.ep_in_enable;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.ep_in_enable = new_val;
    }
    fn read_usbstat(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::Usbstat::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.usbstat)
    }
    fn write_avoutbuffer(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Avoutbuffer::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.avoutbuffer;
        let mut new_val = current_val;
        new_val = (new_val & !(0x1f as caliptra_emu_types::RvData))
            | (write_val & (0x1f as caliptra_emu_types::RvData));
        self.avoutbuffer = new_val;
    }
    fn write_avsetupbuffer(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Avsetupbuffer::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.avsetupbuffer;
        let mut new_val = current_val;
        new_val = (new_val & !(0x1f as caliptra_emu_types::RvData))
            | (write_val & (0x1f as caliptra_emu_types::RvData));
        self.avsetupbuffer = new_val;
    }
    fn read_rxfifo(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::Rxfifo::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(self.rxfifo)
    }
    fn read_rxenable_setup(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::RxenableSetup::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.rxenable_setup)
    }
    fn write_rxenable_setup(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::RxenableSetup::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.rxenable_setup;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.rxenable_setup = new_val;
    }
    fn read_rxenable_out(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::RxenableOut::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.rxenable_out)
    }
    fn write_rxenable_out(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::RxenableOut::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.rxenable_out;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfff as caliptra_emu_types::RvData))
            | (write_val & (0xfff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xfff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfff_0000 as caliptra_emu_types::RvData));
        self.rxenable_out = new_val;
    }
    fn read_set_nak_out(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::SetNakOut::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.set_nak_out)
    }
    fn write_set_nak_out(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::SetNakOut::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.set_nak_out;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.set_nak_out = new_val;
    }
    fn read_in_sent(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::InSent::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(self.in_sent)
    }
    fn write_in_sent(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InSent::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.in_sent;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.in_sent = new_val;
    }
    fn read_out_stall(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::OutStall::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.out_stall)
    }
    fn write_out_stall(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::OutStall::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.out_stall;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.out_stall = new_val;
    }
    fn read_in_stall(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::InStall::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.in_stall)
    }
    fn write_in_stall(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InStall::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.in_stall;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.in_stall = new_val;
    }
    fn read_configin_0(
        &mut self,
        index: usize,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::Configin0::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.configin_0[index])
    }
    fn write_configin_0(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::Configin0::Register,
        >,
        index: usize,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.configin_0[index];
        let mut new_val = current_val;
        new_val = (new_val & !(0x1f as caliptra_emu_types::RvData))
            | (write_val & (0x1f as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x7f00 as caliptra_emu_types::RvData))
            | (write_val & (0x7f00 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.configin_0[index] = new_val;
    }
    fn read_out_iso(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::OutIso::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(self.out_iso)
    }
    fn write_out_iso(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::OutIso::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.out_iso;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.out_iso = new_val;
    }
    fn read_in_iso(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<u32, registers_generated::usbdev::bits::InIso::Register>
    {
        caliptra_emu_bus::ReadWriteRegister::new(self.in_iso)
    }
    fn write_in_iso(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InIso::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.in_iso;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x100 as caliptra_emu_types::RvData))
            | (write_val & (0x100 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x200 as caliptra_emu_types::RvData))
            | (write_val & (0x200 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x400 as caliptra_emu_types::RvData))
            | (write_val & (0x400 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x800 as caliptra_emu_types::RvData))
            | (write_val & (0x800 as caliptra_emu_types::RvData));
        self.in_iso = new_val;
    }
    fn read_out_data_toggle(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::OutDataToggle::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.out_data_toggle)
    }
    fn write_out_data_toggle(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::OutDataToggle::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.out_data_toggle;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfff as caliptra_emu_types::RvData))
            | (write_val & (0xfff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xfff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfff_0000 as caliptra_emu_types::RvData));
        self.out_data_toggle = new_val;
    }
    fn read_in_data_toggle(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::InDataToggle::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.in_data_toggle)
    }
    fn write_in_data_toggle(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::InDataToggle::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.in_data_toggle;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfff as caliptra_emu_types::RvData))
            | (write_val & (0xfff as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xfff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfff_0000 as caliptra_emu_types::RvData));
        self.in_data_toggle = new_val;
    }
    fn read_phy_pins_sense(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::PhyPinsSense::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.phy_pins_sense)
    }
    fn read_phy_pins_drive(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::PhyPinsDrive::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.phy_pins_drive)
    }
    fn write_phy_pins_drive(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::PhyPinsDrive::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.phy_pins_drive;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(8 as caliptra_emu_types::RvData))
            | (write_val & (8 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x10 as caliptra_emu_types::RvData))
            | (write_val & (0x10 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1_0000 as caliptra_emu_types::RvData));
        self.phy_pins_drive = new_val;
    }
    fn read_phy_config(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::PhyConfig::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.phy_config)
    }
    fn write_phy_config(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::PhyConfig::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.phy_config;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x20 as caliptra_emu_types::RvData))
            | (write_val & (0x20 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x40 as caliptra_emu_types::RvData))
            | (write_val & (0x40 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x80 as caliptra_emu_types::RvData))
            | (write_val & (0x80 as caliptra_emu_types::RvData));
        self.phy_config = new_val;
    }
    fn write_wake_control(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::WakeControl::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.wake_control;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        self.wake_control = new_val;
    }
    fn read_wake_events(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::WakeEvents::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.wake_events)
    }
    fn write_fifo_ctrl(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::FifoCtrl::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.fifo_ctrl;
        let mut new_val = current_val;
        new_val = (new_val & !(1 as caliptra_emu_types::RvData))
            | (write_val & (1 as caliptra_emu_types::RvData));
        new_val = (new_val & !(2 as caliptra_emu_types::RvData))
            | (write_val & (2 as caliptra_emu_types::RvData));
        new_val = (new_val & !(4 as caliptra_emu_types::RvData))
            | (write_val & (4 as caliptra_emu_types::RvData));
        self.fifo_ctrl = new_val;
    }
    fn read_count_out(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountOut::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.count_out)
    }
    fn write_count_out(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountOut::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.count_out;
        let mut new_val = current_val;
        new_val = (new_val & !(0x1000 as caliptra_emu_types::RvData))
            | (write_val & (0x1000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xfff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfff_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.count_out = new_val;
    }
    fn read_count_in(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountIn::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.count_in)
    }
    fn write_count_in(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountIn::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.count_in;
        let mut new_val = current_val;
        new_val = (new_val & !(0x2000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0xfff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfff_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.count_in = new_val;
    }
    fn read_count_nodata_in(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountNodataIn::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.count_nodata_in)
    }
    fn write_count_nodata_in(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountNodataIn::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.count_nodata_in;
        let mut new_val = current_val;
        new_val = (new_val & !(0xfff_0000 as caliptra_emu_types::RvData))
            | (write_val & (0xfff_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.count_nodata_in = new_val;
    }
    fn read_count_errors(
        &mut self,
    ) -> caliptra_emu_bus::ReadWriteRegister<
        u32,
        registers_generated::usbdev::bits::CountErrors::Register,
    > {
        caliptra_emu_bus::ReadWriteRegister::new(self.count_errors)
    }
    fn write_count_errors(
        &mut self,
        val: caliptra_emu_bus::ReadWriteRegister<
            u32,
            registers_generated::usbdev::bits::CountErrors::Register,
        >,
    ) {
        let write_val = (val.reg.get()) as caliptra_emu_types::RvData;
        let current_val = self.count_errors;
        let mut new_val = current_val;
        new_val = (new_val & !(0x800_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x800_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x1000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x1000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x2000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x2000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x4000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x4000_0000 as caliptra_emu_types::RvData));
        new_val = (new_val & !(0x8000_0000 as caliptra_emu_types::RvData))
            | (write_val & (0x8000_0000 as caliptra_emu_types::RvData));
        self.count_errors = new_val;
    }
    fn read_buffer(&mut self, index: usize) -> caliptra_emu_types::RvData {
        self.buffer[index]
    }
    fn write_buffer(&mut self, val: caliptra_emu_types::RvData, index: usize) {
        let write_val = (val) as caliptra_emu_types::RvData;
        let current_val = self.buffer[index];
        let mut new_val = current_val;
        new_val = (new_val & !(0xffff_ffff as caliptra_emu_types::RvData))
            | (write_val & (0xffff_ffff as caliptra_emu_types::RvData));
        self.buffer[index] = new_val;
    }
}
pub struct UsbdevBus {
    pub periph: Box<dyn UsbdevPeripheral>,
}
impl caliptra_emu_bus::Bus for UsbdevBus {
    fn read(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
    ) -> Result<caliptra_emu_types::RvData, caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::LoadAddrMisaligned);
        }
        match addr {
            0..4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_intr_state().reg.get(),
            )),
            4..8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_intr_enable().reg.get(),
            )),
            0x10..0x14 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_usbctrl().reg.get(),
            )),
            0x14..0x18 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ep_out_enable().reg.get(),
            )),
            0x18..0x1c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_ep_in_enable().reg.get(),
            )),
            0x1c..0x20 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_usbstat().reg.get(),
            )),
            0x28..0x2c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_rxfifo().reg.get(),
            )),
            0x2c..0x30 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_rxenable_setup().reg.get(),
            )),
            0x30..0x34 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_rxenable_out().reg.get(),
            )),
            0x34..0x38 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_set_nak_out().reg.get(),
            )),
            0x38..0x3c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_in_sent().reg.get(),
            )),
            0x3c..0x40 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_out_stall().reg.get(),
            )),
            0x40..0x44 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_in_stall().reg.get(),
            )),
            0x44..0x74 => Ok(caliptra_emu_types::RvData::from(
                self.periph
                    .read_configin_0((addr as usize - 0x44) / 4)
                    .reg
                    .get(),
            )),
            0x74..0x78 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_out_iso().reg.get(),
            )),
            0x78..0x7c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_in_iso().reg.get(),
            )),
            0x7c..0x80 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_out_data_toggle().reg.get(),
            )),
            0x80..0x84 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_in_data_toggle().reg.get(),
            )),
            0x84..0x88 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_phy_pins_sense().reg.get(),
            )),
            0x88..0x8c => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_phy_pins_drive().reg.get(),
            )),
            0x8c..0x90 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_phy_config().reg.get(),
            )),
            0x94..0x98 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_wake_events().reg.get(),
            )),
            0x9c..0xa0 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_count_out().reg.get(),
            )),
            0xa0..0xa4 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_count_in().reg.get(),
            )),
            0xa4..0xa8 => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_count_nodata_in().reg.get(),
            )),
            0xa8..0xac => Ok(caliptra_emu_types::RvData::from(
                self.periph.read_count_errors().reg.get(),
            )),
            0x800..0x1000 => Ok(self.periph.read_buffer((addr as usize - 0x800) / 4)),
            _ => Err(caliptra_emu_bus::BusError::LoadAccessFault),
        }
    }
    fn write(
        &mut self,
        size: caliptra_emu_types::RvSize,
        addr: caliptra_emu_types::RvAddr,
        val: caliptra_emu_types::RvData,
    ) -> Result<(), caliptra_emu_bus::BusError> {
        if addr & 0x3 != 0 || size != caliptra_emu_types::RvSize::Word {
            return Err(caliptra_emu_bus::BusError::StoreAddrMisaligned);
        }
        match addr {
            0..4 => {
                self.periph
                    .write_intr_state(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            4..8 => {
                self.periph
                    .write_intr_enable(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            8..0xc => {
                self.periph
                    .write_intr_test(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xc..0x10 => {
                self.periph
                    .write_alert_test(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x10..0x14 => {
                self.periph
                    .write_usbctrl(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x14..0x18 => {
                self.periph
                    .write_ep_out_enable(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x18..0x1c => {
                self.periph
                    .write_ep_in_enable(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x1c..0x20 => Ok(()),
            0x20..0x24 => {
                self.periph
                    .write_avoutbuffer(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x24..0x28 => {
                self.periph
                    .write_avsetupbuffer(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x28..0x2c => Ok(()),
            0x2c..0x30 => {
                self.periph
                    .write_rxenable_setup(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x30..0x34 => {
                self.periph
                    .write_rxenable_out(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x34..0x38 => {
                self.periph
                    .write_set_nak_out(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x38..0x3c => {
                self.periph
                    .write_in_sent(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x3c..0x40 => {
                self.periph
                    .write_out_stall(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x40..0x44 => {
                self.periph
                    .write_in_stall(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x44..0x74 => {
                self.periph.write_configin_0(
                    caliptra_emu_bus::ReadWriteRegister::new(val),
                    (addr as usize - 0x44) / 4,
                );
                Ok(())
            }
            0x74..0x78 => {
                self.periph
                    .write_out_iso(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x78..0x7c => {
                self.periph
                    .write_in_iso(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x7c..0x80 => {
                self.periph
                    .write_out_data_toggle(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x80..0x84 => {
                self.periph
                    .write_in_data_toggle(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x84..0x88 => Ok(()),
            0x88..0x8c => {
                self.periph
                    .write_phy_pins_drive(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x8c..0x90 => {
                self.periph
                    .write_phy_config(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x90..0x94 => {
                self.periph
                    .write_wake_control(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x94..0x98 => Ok(()),
            0x98..0x9c => {
                self.periph
                    .write_fifo_ctrl(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x9c..0xa0 => {
                self.periph
                    .write_count_out(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xa0..0xa4 => {
                self.periph
                    .write_count_in(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xa4..0xa8 => {
                self.periph
                    .write_count_nodata_in(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0xa8..0xac => {
                self.periph
                    .write_count_errors(caliptra_emu_bus::ReadWriteRegister::new(val));
                Ok(())
            }
            0x800..0x1000 => {
                self.periph.write_buffer(val, (addr as usize - 0x800) / 4);
                Ok(())
            }
            _ => Err(caliptra_emu_bus::BusError::StoreAccessFault),
        }
    }
    fn poll(&mut self) {
        self.periph.poll();
    }
    fn warm_reset(&mut self) {
        self.periph.warm_reset();
    }
    fn update_reset(&mut self) {
        self.periph.update_reset();
    }
}
