# Licensed under the Apache-2.0 license

name: Size History

on:
  push:
    branches: ["main"]
  pull_request:
  merge_group:

  workflow_dispatch:

permissions:
  contents: read

jobs:
  analyze:
    runs-on: ubuntu-24.04

    env:
      CARGO_INCREMENTAL: 0
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
      EVENT_NAME: ${{ github.event_name }}
      PR_TITLE: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || '' }}
      PR_BASE_COMMIT: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || '' }}
      GIT_AUTHOR_NAME: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login || github.actor }}
      GIT_AUTHOR_EMAIL: ${{ github.event_name == 'pull_request' && format('{0}+{1}@users.noreply.github.com', github.event.pull_request.user.id, github.event.pull_request.user.login) || format('{0}+{1}@users.noreply.github.com', github.actor_id, github.actor) }}
      GIT_COMMITTER_NAME: ${{ github.event_name == 'pull_request' && github.event.pull_request.user.login || github.actor }}
      GIT_COMMITTER_EMAIL: ${{ github.event_name == 'pull_request' && format('{0}+{1}@users.noreply.github.com', github.event.pull_request.user.id, github.event.pull_request.user.login) || format('{0}+{1}@users.noreply.github.com', github.actor_id, github.actor) }}

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive
          ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || github.sha }}
      - name: Configure actions-cache environment variables
        uses: actions/github-script@v9
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            core.exportVariable('ACTIONS_CACHE_SERVICE_V2', 'on');

      - name: Run size analysis (look at workflow "Summary" tab for results)
        run: |
          cargo xtask ci size-history
